// Generated by GenerateNativeBindings.py; do not edit.
#include "LhatNativeBindings.h"
PRAGMA_DISABLE_DEPRECATION_WARNINGS
#include "Camera/CameraActor.h"
#include "GameFramework/Actor.h"
#include "GameFramework/PlayerController.h"
#include "Kismet/KismetSystemLibrary.h"
#include "UObject/Object.h"
namespace {
static void Call0(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UObject* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetSystemLibrary::GetDisplayName(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call1(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UObject* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetSystemLibrary::GetOuterObject(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call2(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetSystemLibrary::GetEngineVersion();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call3(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetSystemLibrary::GetBuildVersion();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call4(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetSystemLibrary::GetBuildConfiguration();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call5(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetSystemLibrary::GetGameName();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call6(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetSystemLibrary::GetProjectDirectory();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call7(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetSystemLibrary::GetProjectContentDirectory();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call8(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetSystemLibrary::GetProjectSavedDirectory();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call9(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FString Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetSystemLibrary::ConvertToRelativePath(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call10(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FString Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetSystemLibrary::ConvertToAbsolutePath(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call11(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FString Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetSystemLibrary::NormalizeFilename(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call12(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetSystemLibrary::GetGameBundleId();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call13(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetSystemLibrary::GetPlatformUserName();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call14(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetSystemLibrary::GetPlatformUserDir();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call15(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UObject* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetSystemLibrary::GetGameTimeInSeconds(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call16(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetSystemLibrary::GetFrameCount();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call17(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UObject* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetSystemLibrary::IsServer(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call18(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UObject* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetSystemLibrary::IsDedicatedServer(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call19(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UObject* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetSystemLibrary::IsStandalone(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call20(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UObject* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetSystemLibrary::IsSplitScreen(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call21(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UObject* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetSystemLibrary::HasMultipleLocalPlayers(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call22(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetSystemLibrary::IsPackagedForDistribution();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call23(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetSystemLibrary::GetUniqueDeviceId();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call24(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetSystemLibrary::GetDeviceId();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call25(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FString Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    bool Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    UKismetSystemLibrary::LogString(Arg0, Arg1);
}
static void Call26(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 7) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UObject* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    FString Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    bool Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    bool Arg3{};
    if (!LhatUEBindings::Read(M, B, Args[3], Arg3)) return;
    FLinearColor Arg4{};
    if (!LhatUEBindings::ReadValue(M, B, Args[4], Arg4, "LinearColor")) return;
    float Arg5{};
    if (!LhatUEBindings::Read(M, B, Args[5], Arg5)) return;
    FName Arg6{};
    if (!LhatUEBindings::Read(M, B, Args[6], Arg6)) return;
    UKismetSystemLibrary::PrintString(Arg0, Arg1, Arg2, Arg3, Arg4, Arg5, Arg6);
}
static void Call27(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FString Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    UKismetSystemLibrary::PrintWarning(Arg0);
}
static void Call28(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UObject* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    FString Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    APlayerController* Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    UKismetSystemLibrary::ExecuteConsoleCommand(Arg0, Arg1, Arg2);
}
static void Call29(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FString Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetSystemLibrary::GetConsoleVariableStringValue(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call30(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FString Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetSystemLibrary::GetConsoleVariableFloatValue(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call31(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FString Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetSystemLibrary::GetConsoleVariableIntValue(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call32(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FString Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetSystemLibrary::GetConsoleVariableBoolValue(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call33(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UObject* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    FString Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    UKismetSystemLibrary::K2_ClearTimer(Arg0, Arg1);
}
static void Call34(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UObject* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    FString Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    UKismetSystemLibrary::K2_PauseTimer(Arg0, Arg1);
}
static void Call35(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UObject* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    FString Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    UKismetSystemLibrary::K2_UnPauseTimer(Arg0, Arg1);
}
static void Call36(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UObject* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    FString Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetSystemLibrary::K2_IsTimerActive(Arg0, Arg1);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call37(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UObject* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    FString Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetSystemLibrary::K2_IsTimerPaused(Arg0, Arg1);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call38(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UObject* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    FString Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetSystemLibrary::K2_TimerExists(Arg0, Arg1);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call39(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UObject* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    FString Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetSystemLibrary::K2_GetTimerElapsedTime(Arg0, Arg1);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call40(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UObject* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    FString Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetSystemLibrary::K2_GetTimerRemainingTime(Arg0, Arg1);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call41(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UObject* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    FName Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    int32 Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    UKismetSystemLibrary::SetIntPropertyByName(Arg0, Arg1, Arg2);
}
static void Call42(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UObject* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    FName Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    int64 Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    UKismetSystemLibrary::SetInt64PropertyByName(Arg0, Arg1, Arg2);
}
static void Call43(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UObject* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    FName Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    uint8 Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    UKismetSystemLibrary::SetBytePropertyByName(Arg0, Arg1, Arg2);
}
static void Call44(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UObject* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    FName Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    double Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    UKismetSystemLibrary::SetDoublePropertyByName(Arg0, Arg1, Arg2);
}
static void Call45(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UObject* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    FName Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    bool Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    UKismetSystemLibrary::SetBoolPropertyByName(Arg0, Arg1, Arg2);
}
static void Call46(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UObject* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    FName Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    UObject* Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    UKismetSystemLibrary::SetObjectPropertyByName(Arg0, Arg1, Arg2);
}
static void Call47(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UObject* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    FName Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    FName Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    UKismetSystemLibrary::SetNamePropertyByName(Arg0, Arg1, Arg2);
}
static void Call48(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UObject* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    FName Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    FString Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    UKismetSystemLibrary::SetStringPropertyByName(Arg0, Arg1, Arg2);
}
static void Call49(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UObject* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    FName Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    FVector Arg2{};
    if (!LhatUEBindings::ReadValue(M, B, Args[2], Arg2, "Vector")) return;
    UKismetSystemLibrary::SetVectorPropertyByName(Arg0, Arg1, Arg2);
}
static void Call50(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UObject* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    FName Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    FRotator Arg2{};
    if (!LhatUEBindings::ReadValue(M, B, Args[2], Arg2, "Rotator")) return;
    UKismetSystemLibrary::SetRotatorPropertyByName(Arg0, Arg1, Arg2);
}
static void Call51(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UObject* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    FName Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    FLinearColor Arg2{};
    if (!LhatUEBindings::ReadValue(M, B, Args[2], Arg2, "LinearColor")) return;
    UKismetSystemLibrary::SetLinearColorPropertyByName(Arg0, Arg1, Arg2);
}
static void Call52(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UObject* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    FName Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    FColor Arg2{};
    if (!LhatUEBindings::ReadValue(M, B, Args[2], Arg2, "Color")) return;
    UKismetSystemLibrary::SetColorPropertyByName(Arg0, Arg1, Arg2);
}
static void Call53(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UObject* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    FName Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    FTransform Arg2{};
    if (!LhatUEBindings::ReadValue(M, B, Args[2], Arg2, "Transform")) return;
    UKismetSystemLibrary::SetTransformPropertyByName(Arg0, Arg1, Arg2);
}
static void Call54(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 10) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UObject* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    FVector Arg2{};
    if (!LhatUEBindings::ReadValue(M, B, Args[2], Arg2, "Vector")) return;
    float Arg3{};
    if (!LhatUEBindings::Read(M, B, Args[3], Arg3)) return;
    float Arg4{};
    if (!LhatUEBindings::Read(M, B, Args[4], Arg4)) return;
    float Arg5{};
    if (!LhatUEBindings::Read(M, B, Args[5], Arg5)) return;
    int32 Arg6{};
    if (!LhatUEBindings::Read(M, B, Args[6], Arg6)) return;
    FLinearColor Arg7{};
    if (!LhatUEBindings::ReadValue(M, B, Args[7], Arg7, "LinearColor")) return;
    float Arg8{};
    if (!LhatUEBindings::Read(M, B, Args[8], Arg8)) return;
    float Arg9{};
    if (!LhatUEBindings::Read(M, B, Args[9], Arg9)) return;
    UKismetSystemLibrary::DrawDebugCone(Arg0, Arg1, Arg2, Arg3, Arg4, Arg5, Arg6, Arg7, Arg8, Arg9);
}
static void Call55(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 6) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UObject* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    FString Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    AActor* Arg3{};
    if (!LhatUEBindings::Read(M, B, Args[3], Arg3)) return;
    FLinearColor Arg4{};
    if (!LhatUEBindings::ReadValue(M, B, Args[4], Arg4, "LinearColor")) return;
    float Arg5{};
    if (!LhatUEBindings::Read(M, B, Args[5], Arg5)) return;
    UKismetSystemLibrary::DrawDebugString(Arg0, Arg1, Arg2, Arg3, Arg4, Arg5);
}
static void Call56(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UObject* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    UKismetSystemLibrary::FlushDebugStrings(Arg0);
}
static void Call57(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UObject* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    UKismetSystemLibrary::FlushPersistentDebugLines(Arg0);
}
static void Call58(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 5) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UObject* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    FTransform Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Transform")) return;
    FLinearColor Arg2{};
    if (!LhatUEBindings::ReadValue(M, B, Args[2], Arg2, "LinearColor")) return;
    float Arg3{};
    if (!LhatUEBindings::Read(M, B, Args[3], Arg3)) return;
    float Arg4{};
    if (!LhatUEBindings::Read(M, B, Args[4], Arg4)) return;
    UKismetSystemLibrary::DrawDebugFrustum(Arg0, Arg1, Arg2, Arg3, Arg4);
}
static void Call59(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    ACameraActor* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    FLinearColor Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "LinearColor")) return;
    float Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    UKismetSystemLibrary::DrawDebugCamera(Arg0, Arg1, Arg2);
}
static void Call60(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UObject* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    UKismetSystemLibrary::CreateCopyForUndoBuffer(Arg0);
}
static void Call61(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetSystemLibrary::GetRenderingDetailMode();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call62(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetSystemLibrary::GetRenderingMaterialQualityLevel();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call63(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetSystemLibrary::GetMinYResolutionForUI();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call64(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetSystemLibrary::GetMinYResolutionFor3DView();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call65(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FString Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    UKismetSystemLibrary::LaunchURL(Arg0);
}
static void Call66(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FString Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetSystemLibrary::CanLaunchURL(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call67(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UKismetSystemLibrary::CollectGarbage();
}
static void Call68(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    int32 Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    bool Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    UKismetSystemLibrary::ShowAdBanner(Arg0, Arg1);
}
static void Call69(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetSystemLibrary::GetAdIDCount();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call70(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UKismetSystemLibrary::HideAdBanner();
}
static void Call71(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UKismetSystemLibrary::ForceCloseAdBanner();
}
static void Call72(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    int32 Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    UKismetSystemLibrary::LoadInterstitialAd(Arg0);
}
static void Call73(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetSystemLibrary::IsInterstitialAdAvailable();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call74(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetSystemLibrary::IsInterstitialAdRequested();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call75(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UKismetSystemLibrary::ShowInterstitialAd();
}
static void Call76(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FString Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    UKismetSystemLibrary::ShowPlatformSpecificLeaderboardScreen(Arg0);
}
static void Call77(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    APlayerController* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    UKismetSystemLibrary::ShowPlatformSpecificAchievementsScreen(Arg0);
}
static void Call78(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    APlayerController* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetSystemLibrary::IsLoggedIn(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call79(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetSystemLibrary::IsScreensaverEnabled();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
}
void Gather_LhatBundledRuntime_Engine_9(TArray<FLhatNativeType>& Types)
{
}
bool Register_LhatBundledRuntime_Engine_9(LhatProgram* P, FLhatBindings& B)
{
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "GetDisplayName", "f^ue.Object|nil^ -> string^;", Call0, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "GetOuterObject", "f^ue.Object|nil^ -> ue.Object|nil^;", Call1, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "GetEngineVersion", "f^ -> string^;", Call2, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "GetBuildVersion", "f^ -> string^;", Call3, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "GetBuildConfiguration", "f^ -> string^;", Call4, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "GetGameName", "f^ -> string^;", Call5, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "GetProjectDirectory", "f^ -> string^;", Call6, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "GetProjectContentDirectory", "f^ -> string^;", Call7, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "GetProjectSavedDirectory", "f^ -> string^;", Call8, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "ConvertToRelativePath", "f^string^ -> string^;", Call9, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "ConvertToAbsolutePath", "f^string^ -> string^;", Call10, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "NormalizeFilename", "f^string^ -> string^;", Call11, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "GetGameBundleId", "f^ -> string^;", Call12, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "GetPlatformUserName", "f^ -> string^;", Call13, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "GetPlatformUserDir", "f^ -> string^;", Call14, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "GetGameTimeInSeconds", "f^ue.Object|nil^ -> number^;", Call15, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "GetFrameCount", "f^ -> number^;", Call16, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "IsServer", "f^ue.Object|nil^ -> bool^;", Call17, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "IsDedicatedServer", "f^ue.Object|nil^ -> bool^;", Call18, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "IsStandalone", "f^ue.Object|nil^ -> bool^;", Call19, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "IsSplitScreen", "f^ue.Object|nil^ -> bool^;", Call20, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "HasMultipleLocalPlayers", "f^ue.Object|nil^ -> bool^;", Call21, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "IsPackagedForDistribution", "f^ -> bool^;", Call22, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "GetUniqueDeviceId", "f^ -> string^;", Call23, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "GetDeviceId", "f^ -> string^;", Call24, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "LogString", "p^string^, bool^;", Call25, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "PrintString", "p^ue.Object|nil^, string^, bool^, bool^, ue.LinearColor, number^, string^;", Call26, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "PrintWarning", "p^string^;", Call27, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "ExecuteConsoleCommand", "p^ue.Object|nil^, string^, ue.Engine.PlayerController|nil^;", Call28, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "GetConsoleVariableStringValue", "p^string^ -> string^;", Call29, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "GetConsoleVariableFloatValue", "p^string^ -> number^;", Call30, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "GetConsoleVariableIntValue", "p^string^ -> number^;", Call31, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "GetConsoleVariableBoolValue", "p^string^ -> bool^;", Call32, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "K2_ClearTimer", "p^ue.Object|nil^, string^;", Call33, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "K2_PauseTimer", "p^ue.Object|nil^, string^;", Call34, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "K2_UnPauseTimer", "p^ue.Object|nil^, string^;", Call35, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "K2_IsTimerActive", "f^ue.Object|nil^, string^ -> bool^;", Call36, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "K2_IsTimerPaused", "f^ue.Object|nil^, string^ -> bool^;", Call37, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "K2_TimerExists", "f^ue.Object|nil^, string^ -> bool^;", Call38, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "K2_GetTimerElapsedTime", "f^ue.Object|nil^, string^ -> number^;", Call39, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "K2_GetTimerRemainingTime", "f^ue.Object|nil^, string^ -> number^;", Call40, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "SetIntPropertyByName", "p^ue.Object|nil^, string^, number^;", Call41, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "SetInt64PropertyByName", "p^ue.Object|nil^, string^, number^;", Call42, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "SetBytePropertyByName", "p^ue.Object|nil^, string^, number^;", Call43, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "SetDoublePropertyByName", "p^ue.Object|nil^, string^, number^;", Call44, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "SetBoolPropertyByName", "p^ue.Object|nil^, string^, bool^;", Call45, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "SetObjectPropertyByName", "p^ue.Object|nil^, string^, ue.Object|nil^;", Call46, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "SetNamePropertyByName", "p^ue.Object|nil^, string^, string^;", Call47, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "SetStringPropertyByName", "p^ue.Object|nil^, string^, string^;", Call48, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "SetVectorPropertyByName", "p^ue.Object|nil^, string^, ue.Vector;", Call49, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "SetRotatorPropertyByName", "p^ue.Object|nil^, string^, ue.Rotator;", Call50, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "SetLinearColorPropertyByName", "p^ue.Object|nil^, string^, ue.LinearColor;", Call51, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "SetColorPropertyByName", "p^ue.Object|nil^, string^, ue.Color;", Call52, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "SetTransformPropertyByName", "p^ue.Object|nil^, string^, ue.Transform;", Call53, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "DrawDebugCone", "p^ue.Object|nil^, ue.Vector, ue.Vector, number^, number^, number^, number^, ue.LinearColor, number^, number^;", Call54, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "DrawDebugString", "p^ue.Object|nil^, ue.Vector, string^, ue.Actor|nil^, ue.LinearColor, number^;", Call55, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "FlushDebugStrings", "p^ue.Object|nil^;", Call56, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "FlushPersistentDebugLines", "p^ue.Object|nil^;", Call57, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "DrawDebugFrustum", "p^ue.Object|nil^, ue.Transform, ue.LinearColor, number^, number^;", Call58, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "DrawDebugCamera", "p^ue.Engine.CameraActor|nil^, ue.LinearColor, number^;", Call59, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "CreateCopyForUndoBuffer", "p^ue.Object|nil^;", Call60, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "GetRenderingDetailMode", "f^ -> number^;", Call61, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "GetRenderingMaterialQualityLevel", "f^ -> number^;", Call62, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "GetMinYResolutionForUI", "f^ -> number^;", Call63, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "GetMinYResolutionFor3DView", "f^ -> number^;", Call64, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "LaunchURL", "p^string^;", Call65, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "CanLaunchURL", "p^string^ -> bool^;", Call66, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "CollectGarbage", "p^;", Call67, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "ShowAdBanner", "p^number^, bool^;", Call68, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "GetAdIDCount", "f^ -> number^;", Call69, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "HideAdBanner", "p^;", Call70, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "ForceCloseAdBanner", "p^;", Call71, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "LoadInterstitialAd", "p^number^;", Call72, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "IsInterstitialAdAvailable", "p^ -> bool^;", Call73, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "IsInterstitialAdRequested", "p^ -> bool^;", Call74, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "ShowInterstitialAd", "p^;", Call75, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "ShowPlatformSpecificLeaderboardScreen", "p^string^;", Call76, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "ShowPlatformSpecificAchievementsScreen", "p^ue.Engine.PlayerController|nil^;", Call77, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "IsLoggedIn", "f^ue.Engine.PlayerController|nil^ -> bool^;", Call78, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "IsScreensaverEnabled", "p^ -> bool^;", Call79, &B)) return false;
    return true;
}
PRAGMA_ENABLE_DEPRECATION_WARNINGS
