// Generated by GenerateNativeBindings.py; do not edit.
#include "LhatNativeBindings.h"
PRAGMA_DISABLE_DEPRECATION_WARNINGS
#include "Kismet/KismetMathLibrary.h"
namespace {
static void Call0(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    double Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetMathLibrary::Tan(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call1(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    double Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetMathLibrary::Atan(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call2(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    double Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    double Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetMathLibrary::Atan2(Arg0, Arg1);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call3(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    double Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetMathLibrary::Exp(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call4(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    double Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    double Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetMathLibrary::Log(Arg0, Arg1);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call5(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    double Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetMathLibrary::Loge(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call6(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    double Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetMathLibrary::Sqrt(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call7(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    double Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetMathLibrary::Square(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call8(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetMathLibrary::RandomFloat();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call9(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    double Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    double Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetMathLibrary::RandomFloatInRange(Arg0, Arg1);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call10(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetMathLibrary::GetPI();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call11(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetMathLibrary::GetTAU();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call12(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    double Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetMathLibrary::DegreesToRadians(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call13(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    double Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetMathLibrary::RadiansToDegrees(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call14(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    double Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetMathLibrary::DegSin(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call15(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    double Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetMathLibrary::DegAsin(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call16(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    double Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetMathLibrary::DegCos(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call17(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    double Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetMathLibrary::DegAcos(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call18(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    double Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetMathLibrary::DegTan(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call19(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    double Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetMathLibrary::DegAtan(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call20(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    double Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    double Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetMathLibrary::DegAtan2(Arg0, Arg1);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call21(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    double Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    double Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    double Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    const auto Result = UKismetMathLibrary::ClampAngle(Arg0, Arg1, Arg2);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call22(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    double Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    double Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetMathLibrary::FMin(Arg0, Arg1);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call23(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    double Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    double Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetMathLibrary::FMax(Arg0, Arg1);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call24(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    double Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    double Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    double Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    const auto Result = UKismetMathLibrary::FClamp(Arg0, Arg1, Arg2);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call25(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    double Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    double Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    double Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    const auto Result = UKismetMathLibrary::FWrap(Arg0, Arg1, Arg2);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call26(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    double Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    double Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetMathLibrary::SafeDivide(Arg0, Arg1);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call27(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    double Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    double Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    double Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    const auto Result = UKismetMathLibrary::Lerp(Arg0, Arg1, Arg2);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call28(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    double Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetMathLibrary::Round(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call29(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    double Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetMathLibrary::FFloor(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call30(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    double Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetMathLibrary::FTrunc(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call31(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    double Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetMathLibrary::FCeil(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call32(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    double Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetMathLibrary::Round64(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call33(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    double Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetMathLibrary::FFloor64(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call34(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    double Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetMathLibrary::FTrunc64(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call35(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    double Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetMathLibrary::FCeil64(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call36(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    double Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetMathLibrary::SignOfFloat(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call37(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    double Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    double Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    double Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    const auto Result = UKismetMathLibrary::NormalizeToRange(Arg0, Arg1, Arg2);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call38(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 5) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    double Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    double Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    double Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    double Arg3{};
    if (!LhatUEBindings::Read(M, B, Args[3], Arg3)) return;
    double Arg4{};
    if (!LhatUEBindings::Read(M, B, Args[4], Arg4)) return;
    const auto Result = UKismetMathLibrary::MapRangeUnclamped(Arg0, Arg1, Arg2, Arg3, Arg4);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call39(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 5) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    double Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    double Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    double Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    double Arg3{};
    if (!LhatUEBindings::Read(M, B, Args[3], Arg3)) return;
    double Arg4{};
    if (!LhatUEBindings::Read(M, B, Args[4], Arg4)) return;
    const auto Result = UKismetMathLibrary::MapRangeClamped(Arg0, Arg1, Arg2, Arg3, Arg4);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call40(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    double Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetMathLibrary::MultiplyByPi(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call41(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 4) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    double Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    double Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    double Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    double Arg3{};
    if (!LhatUEBindings::Read(M, B, Args[3], Arg3)) return;
    const auto Result = UKismetMathLibrary::FInterpEaseInOut(Arg0, Arg1, Arg2, Arg3);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call42(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    float Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    float Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    float Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    const auto Result = UKismetMathLibrary::MakePulsatingValue(Arg0, Arg1, Arg2);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call43(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    float Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    float Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    float Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    const auto Result = UKismetMathLibrary::FixedTurn(Arg0, Arg1, Arg2);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call44(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetMathLibrary::Vector2D_One();
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector2D")) *AnswerCount = 1;
}
static void Call45(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetMathLibrary::Vector2D_Unit45Deg();
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector2D")) *AnswerCount = 1;
}
static void Call46(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetMathLibrary::Vector2D_Zero();
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector2D")) *AnswerCount = 1;
}
static void Call47(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    double Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    double Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetMathLibrary::MakeVector2D(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector2D")) *AnswerCount = 1;
}
static void Call48(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector2D Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector2D")) return;
    float Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetMathLibrary::Conv_Vector2DToVector(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call49(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector2D Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector2D")) return;
    FVector2D Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector2D")) return;
    const auto Result = UKismetMathLibrary::Add_Vector2DVector2D(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector2D")) *AnswerCount = 1;
}
static void Call50(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector2D Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector2D")) return;
    double Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetMathLibrary::Add_Vector2DFloat(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector2D")) *AnswerCount = 1;
}
static void Call51(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector2D Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector2D")) return;
    FVector2D Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector2D")) return;
    const auto Result = UKismetMathLibrary::Subtract_Vector2DVector2D(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector2D")) *AnswerCount = 1;
}
static void Call52(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector2D Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector2D")) return;
    double Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetMathLibrary::Subtract_Vector2DFloat(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector2D")) *AnswerCount = 1;
}
static void Call53(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector2D Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector2D")) return;
    FVector2D Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector2D")) return;
    const auto Result = UKismetMathLibrary::Multiply_Vector2DVector2D(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector2D")) *AnswerCount = 1;
}
static void Call54(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector2D Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector2D")) return;
    double Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetMathLibrary::Multiply_Vector2DFloat(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector2D")) *AnswerCount = 1;
}
static void Call55(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector2D Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector2D")) return;
    FVector2D Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector2D")) return;
    const auto Result = UKismetMathLibrary::Divide_Vector2DVector2D(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector2D")) *AnswerCount = 1;
}
static void Call56(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector2D Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector2D")) return;
    double Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetMathLibrary::Divide_Vector2DFloat(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector2D")) *AnswerCount = 1;
}
static void Call57(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector2D Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector2D")) return;
    FVector2D Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector2D")) return;
    const auto Result = UKismetMathLibrary::EqualExactly_Vector2DVector2D(Arg0, Arg1);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call58(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector2D Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector2D")) return;
    FVector2D Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector2D")) return;
    float Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    const auto Result = UKismetMathLibrary::EqualEqual_Vector2DVector2D(Arg0, Arg1, Arg2);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call59(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector2D Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector2D")) return;
    FVector2D Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector2D")) return;
    const auto Result = UKismetMathLibrary::NotEqualExactly_Vector2DVector2D(Arg0, Arg1);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call60(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector2D Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector2D")) return;
    FVector2D Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector2D")) return;
    float Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    const auto Result = UKismetMathLibrary::NotEqual_Vector2DVector2D(Arg0, Arg1, Arg2);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call61(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector2D Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector2D")) return;
    const auto Result = UKismetMathLibrary::Negated2D(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector2D")) *AnswerCount = 1;
}
static void Call62(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector2D Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector2D")) return;
    double Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    double Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    const auto Result = UKismetMathLibrary::ClampAxes2D(Arg0, Arg1, Arg2);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector2D")) *AnswerCount = 1;
}
static void Call63(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector2D Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector2D")) return;
    FVector2D Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector2D")) return;
    const auto Result = UKismetMathLibrary::CrossProduct2D(Arg0, Arg1);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call64(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector2D Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector2D")) return;
    FVector2D Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector2D")) return;
    const auto Result = UKismetMathLibrary::Distance2D(Arg0, Arg1);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call65(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector2D Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector2D")) return;
    FVector2D Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector2D")) return;
    const auto Result = UKismetMathLibrary::DistanceSquared2D(Arg0, Arg1);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call66(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector2D Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector2D")) return;
    FVector2D Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector2D")) return;
    const auto Result = UKismetMathLibrary::DotProduct2D(Arg0, Arg1);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call67(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector2D Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector2D")) return;
    const auto Result = UKismetMathLibrary::GetAbs2D(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector2D")) *AnswerCount = 1;
}
static void Call68(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector2D Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector2D")) return;
    const auto Result = UKismetMathLibrary::GetAbsMax2D(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call69(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector2D Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector2D")) return;
    const auto Result = UKismetMathLibrary::GetMax2D(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call70(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector2D Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector2D")) return;
    const auto Result = UKismetMathLibrary::GetMin2D(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call71(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector2D Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector2D")) return;
    float Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetMathLibrary::GetRotated2D(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector2D")) *AnswerCount = 1;
}
static void Call72(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector2D Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector2D")) return;
    float Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetMathLibrary::IsNearlyZero2D(Arg0, Arg1);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call73(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector2D Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector2D")) return;
    const auto Result = UKismetMathLibrary::IsZero2D(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call74(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 4) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector2D Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector2D")) return;
    FVector2D Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector2D")) return;
    float Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    float Arg3{};
    if (!LhatUEBindings::Read(M, B, Args[3], Arg3)) return;
    const auto Result = UKismetMathLibrary::Vector2DInterpTo(Arg0, Arg1, Arg2, Arg3);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector2D")) *AnswerCount = 1;
}
static void Call75(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 4) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector2D Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector2D")) return;
    FVector2D Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector2D")) return;
    float Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    float Arg3{};
    if (!LhatUEBindings::Read(M, B, Args[3], Arg3)) return;
    const auto Result = UKismetMathLibrary::Vector2DInterpTo_Constant(Arg0, Arg1, Arg2, Arg3);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector2D")) *AnswerCount = 1;
}
static void Call76(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector2D Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector2D")) return;
    float Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetMathLibrary::NormalSafe2D(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector2D")) *AnswerCount = 1;
}
static void Call77(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector2D Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector2D")) return;
    const auto Result = UKismetMathLibrary::Normal2D(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector2D")) *AnswerCount = 1;
}
static void Call78(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector2D Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector2D")) return;
    const auto Result = UKismetMathLibrary::Spherical2DToUnitCartesian(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call79(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector2D Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector2D")) return;
    const auto Result = UKismetMathLibrary::ToRounded2D(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector2D")) *AnswerCount = 1;
}
}
void Gather_LhatBundledRuntime_Engine_4(TArray<FLhatNativeType>& Types)
{
}
bool Register_LhatBundledRuntime_Engine_4(LhatProgram* P, FLhatBindings& B)
{
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Tan", "f^number^ -> number^;", Call0, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Atan", "f^number^ -> number^;", Call1, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Atan2", "f^number^, number^ -> number^;", Call2, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Exp", "f^number^ -> number^;", Call3, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Log", "f^number^, number^ -> number^;", Call4, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Loge", "f^number^ -> number^;", Call5, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Sqrt", "f^number^ -> number^;", Call6, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Square", "f^number^ -> number^;", Call7, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "RandomFloat", "f^ -> number^;", Call8, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "RandomFloatInRange", "f^number^, number^ -> number^;", Call9, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "GetPI", "f^ -> number^;", Call10, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "GetTAU", "f^ -> number^;", Call11, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "DegreesToRadians", "f^number^ -> number^;", Call12, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "RadiansToDegrees", "f^number^ -> number^;", Call13, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "DegSin", "f^number^ -> number^;", Call14, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "DegAsin", "f^number^ -> number^;", Call15, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "DegCos", "f^number^ -> number^;", Call16, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "DegAcos", "f^number^ -> number^;", Call17, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "DegTan", "f^number^ -> number^;", Call18, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "DegAtan", "f^number^ -> number^;", Call19, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "DegAtan2", "f^number^, number^ -> number^;", Call20, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "ClampAngle", "f^number^, number^, number^ -> number^;", Call21, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "FMin", "f^number^, number^ -> number^;", Call22, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "FMax", "f^number^, number^ -> number^;", Call23, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "FClamp", "f^number^, number^, number^ -> number^;", Call24, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "FWrap", "f^number^, number^, number^ -> number^;", Call25, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "SafeDivide", "f^number^, number^ -> number^;", Call26, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Lerp", "f^number^, number^, number^ -> number^;", Call27, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Round", "f^number^ -> number^;", Call28, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "FFloor", "f^number^ -> number^;", Call29, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "FTrunc", "f^number^ -> number^;", Call30, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "FCeil", "f^number^ -> number^;", Call31, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Round64", "f^number^ -> number^;", Call32, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "FFloor64", "f^number^ -> number^;", Call33, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "FTrunc64", "f^number^ -> number^;", Call34, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "FCeil64", "f^number^ -> number^;", Call35, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "SignOfFloat", "f^number^ -> number^;", Call36, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "NormalizeToRange", "f^number^, number^, number^ -> number^;", Call37, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "MapRangeUnclamped", "f^number^, number^, number^, number^, number^ -> number^;", Call38, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "MapRangeClamped", "f^number^, number^, number^, number^, number^ -> number^;", Call39, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "MultiplyByPi", "f^number^ -> number^;", Call40, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "FInterpEaseInOut", "f^number^, number^, number^, number^ -> number^;", Call41, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "MakePulsatingValue", "f^number^, number^, number^ -> number^;", Call42, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "FixedTurn", "f^number^, number^, number^ -> number^;", Call43, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector2D_One", "f^ -> ue.Vector2D;", Call44, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector2D_Unit45Deg", "f^ -> ue.Vector2D;", Call45, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector2D_Zero", "f^ -> ue.Vector2D;", Call46, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "MakeVector2D", "f^number^, number^ -> ue.Vector2D;", Call47, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Conv_Vector2DToVector", "f^ue.Vector2D, number^ -> ue.Vector;", Call48, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Add_Vector2DVector2D", "f^ue.Vector2D, ue.Vector2D -> ue.Vector2D;", Call49, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Add_Vector2DFloat", "f^ue.Vector2D, number^ -> ue.Vector2D;", Call50, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Subtract_Vector2DVector2D", "f^ue.Vector2D, ue.Vector2D -> ue.Vector2D;", Call51, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Subtract_Vector2DFloat", "f^ue.Vector2D, number^ -> ue.Vector2D;", Call52, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Multiply_Vector2DVector2D", "f^ue.Vector2D, ue.Vector2D -> ue.Vector2D;", Call53, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Multiply_Vector2DFloat", "f^ue.Vector2D, number^ -> ue.Vector2D;", Call54, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Divide_Vector2DVector2D", "f^ue.Vector2D, ue.Vector2D -> ue.Vector2D;", Call55, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Divide_Vector2DFloat", "f^ue.Vector2D, number^ -> ue.Vector2D;", Call56, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "EqualExactly_Vector2DVector2D", "f^ue.Vector2D, ue.Vector2D -> bool^;", Call57, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "EqualEqual_Vector2DVector2D", "f^ue.Vector2D, ue.Vector2D, number^ -> bool^;", Call58, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "NotEqualExactly_Vector2DVector2D", "f^ue.Vector2D, ue.Vector2D -> bool^;", Call59, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "NotEqual_Vector2DVector2D", "f^ue.Vector2D, ue.Vector2D, number^ -> bool^;", Call60, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Negated2D", "f^ue.Vector2D -> ue.Vector2D;", Call61, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "ClampAxes2D", "f^ue.Vector2D, number^, number^ -> ue.Vector2D;", Call62, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "CrossProduct2D", "f^ue.Vector2D, ue.Vector2D -> number^;", Call63, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Distance2D", "f^ue.Vector2D, ue.Vector2D -> number^;", Call64, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "DistanceSquared2D", "f^ue.Vector2D, ue.Vector2D -> number^;", Call65, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "DotProduct2D", "f^ue.Vector2D, ue.Vector2D -> number^;", Call66, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "GetAbs2D", "f^ue.Vector2D -> ue.Vector2D;", Call67, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "GetAbsMax2D", "f^ue.Vector2D -> number^;", Call68, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "GetMax2D", "f^ue.Vector2D -> number^;", Call69, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "GetMin2D", "f^ue.Vector2D -> number^;", Call70, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "GetRotated2D", "f^ue.Vector2D, number^ -> ue.Vector2D;", Call71, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "IsNearlyZero2D", "f^ue.Vector2D, number^ -> bool^;", Call72, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "IsZero2D", "f^ue.Vector2D -> bool^;", Call73, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector2DInterpTo", "f^ue.Vector2D, ue.Vector2D, number^, number^ -> ue.Vector2D;", Call74, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector2DInterpTo_Constant", "f^ue.Vector2D, ue.Vector2D, number^, number^ -> ue.Vector2D;", Call75, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "NormalSafe2D", "f^ue.Vector2D, number^ -> ue.Vector2D;", Call76, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Normal2D", "f^ue.Vector2D -> ue.Vector2D;", Call77, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Spherical2DToUnitCartesian", "f^ue.Vector2D -> ue.Vector;", Call78, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "ToRounded2D", "f^ue.Vector2D -> ue.Vector2D;", Call79, &B)) return false;
    return true;
}
PRAGMA_ENABLE_DEPRECATION_WARNINGS
