// Generated by GenerateNativeBindings.py; do not edit.
#include "LhatNativeBindings.h"
PRAGMA_DISABLE_DEPRECATION_WARNINGS
#include "Components/SkeletalMeshComponent.h"
#include "Components/StaticMeshComponent.h"
#include "Engine/StaticMesh.h"
#include "PhysicsEngine/PhysicsAsset.h"
namespace {
static void Call0(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<USkeletalMeshComponent*>(B.ReadObject(M, Args[0], USkeletalMeshComponent::StaticClass()));
    if (!Self) return;
    int32 Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    const auto Result = Self->FindConstraintBoneName(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call1(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 4) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<USkeletalMeshComponent*>(B.ReadObject(M, Args[0], USkeletalMeshComponent::StaticClass()));
    if (!Self) return;
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[2], Arg1, "Vector")) return;
    FName Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[3], Arg2)) return;
    Self->BreakConstraint(Arg0, Arg1, Arg2);
}
static void Call2(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 5) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<USkeletalMeshComponent*>(B.ReadObject(M, Args[0], USkeletalMeshComponent::StaticClass()));
    if (!Self) return;
    FName Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    float Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg1)) return;
    float Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[3], Arg2)) return;
    float Arg3{};
    if (!LhatUEBindings::Read(M, B, Args[4], Arg3)) return;
    Self->SetAngularLimits(Arg0, Arg1, Arg2, Arg3);
}
static void Call3(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<USkeletalMeshComponent*>(B.ReadObject(M, Args[0], USkeletalMeshComponent::StaticClass()));
    if (!Self) return;
    Self->RecreateClothingActors();
}
static void Call4(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<USkeletalMeshComponent*>(B.ReadObject(M, Args[0], USkeletalMeshComponent::StaticClass()));
    if (!Self) return;
    USkeletalMeshComponent* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    UPhysicsAsset* Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg1)) return;
    Self->AddClothCollisionSource(Arg0, Arg1);
}
static void Call5(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<USkeletalMeshComponent*>(B.ReadObject(M, Args[0], USkeletalMeshComponent::StaticClass()));
    if (!Self) return;
    USkeletalMeshComponent* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    Self->RemoveClothCollisionSources(Arg0);
}
static void Call6(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<USkeletalMeshComponent*>(B.ReadObject(M, Args[0], USkeletalMeshComponent::StaticClass()));
    if (!Self) return;
    USkeletalMeshComponent* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    UPhysicsAsset* Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg1)) return;
    Self->RemoveClothCollisionSource(Arg0, Arg1);
}
static void Call7(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<USkeletalMeshComponent*>(B.ReadObject(M, Args[0], USkeletalMeshComponent::StaticClass()));
    if (!Self) return;
    Self->ResetClothCollisionSources();
}
static void Call8(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UStaticMeshComponent*>(B.ReadObject(M, Args[0], UStaticMeshComponent::StaticClass()));
    if (!Self) return;
    UStaticMesh* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    const auto Result = Self->SetStaticMesh(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call9(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UStaticMeshComponent*>(B.ReadObject(M, Args[0], UStaticMeshComponent::StaticClass()));
    if (!Self) return;
    int32 Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    Self->SetForcedLodModel(Arg0);
}
static void Call10(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UStaticMeshComponent*>(B.ReadObject(M, Args[0], UStaticMeshComponent::StaticClass()));
    if (!Self) return;
    float Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    Self->SetDistanceFieldSelfShadowBias(Arg0);
}
static void Call11(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UStaticMeshComponent*>(B.ReadObject(M, Args[0], UStaticMeshComponent::StaticClass()));
    if (!Self) return;
    bool Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    Self->SetEvaluateWorldPositionOffsetInRayTracing(Arg0);
}
static void Call12(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UStaticMeshComponent*>(B.ReadObject(M, Args[0], UStaticMeshComponent::StaticClass()));
    if (!Self) return;
    bool Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    Self->SetEvaluateWorldPositionOffset(Arg0);
}
static void Call13(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UStaticMeshComponent*>(B.ReadObject(M, Args[0], UStaticMeshComponent::StaticClass()));
    if (!Self) return;
    int32 Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    Self->SetWorldPositionOffsetDisableDistance(Arg0);
}
static void Call14(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UStaticMeshComponent*>(B.ReadObject(M, Args[0], UStaticMeshComponent::StaticClass()));
    if (!Self) return;
    bool Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    Self->SetReverseCulling(Arg0);
}
static void Call15(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UStaticMeshComponent*>(B.ReadObject(M, Args[0], UStaticMeshComponent::StaticClass()));
    if (!Self) return;
    bool Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    Self->SetForceDisableNanite(Arg0);
}
}
void Gather_LhatBundledRuntime_Engine_14(TArray<FLhatNativeType>& Types)
{
}
bool Register_LhatBundledRuntime_Engine_14(LhatProgram* P, FLhatBindings& B)
{
    if (!lhat_register_member(P, "ue.Engine", "SkeletalMeshComponent", "FindConstraintBoneName", "p^self^, number^ -> string^;", Call0, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "SkeletalMeshComponent", "BreakConstraint", "p^self^, ue.Vector, ue.Vector, string^;", Call1, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "SkeletalMeshComponent", "SetAngularLimits", "p^self^, string^, number^, number^, number^;", Call2, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "SkeletalMeshComponent", "RecreateClothingActors", "p^self^;", Call3, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "SkeletalMeshComponent", "AddClothCollisionSource", "p^self^, ue.Engine.SkeletalMeshComponent|nil^, ue.Engine.PhysicsAsset|nil^;", Call4, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "SkeletalMeshComponent", "RemoveClothCollisionSources", "p^self^, ue.Engine.SkeletalMeshComponent|nil^;", Call5, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "SkeletalMeshComponent", "RemoveClothCollisionSource", "p^self^, ue.Engine.SkeletalMeshComponent|nil^, ue.Engine.PhysicsAsset|nil^;", Call6, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "SkeletalMeshComponent", "ResetClothCollisionSources", "p^self^;", Call7, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "StaticMeshComponent", "SetStaticMesh", "p^self^, ue.Engine.StaticMesh|nil^ -> bool^;", Call8, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "StaticMeshComponent", "SetForcedLodModel", "p^self^, number^;", Call9, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "StaticMeshComponent", "SetDistanceFieldSelfShadowBias", "p^self^, number^;", Call10, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "StaticMeshComponent", "SetEvaluateWorldPositionOffsetInRayTracing", "p^self^, bool^;", Call11, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "StaticMeshComponent", "SetEvaluateWorldPositionOffset", "p^self^, bool^;", Call12, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "StaticMeshComponent", "SetWorldPositionOffsetDisableDistance", "p^self^, number^;", Call13, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "StaticMeshComponent", "SetReverseCulling", "p^self^, bool^;", Call14, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "StaticMeshComponent", "SetForceDisableNanite", "p^self^, bool^;", Call15, &B)) return false;
    return true;
}
PRAGMA_ENABLE_DEPRECATION_WARNINGS
