// Generated by GenerateNativeBindings.py; do not edit.
#include "LhatNativeBindings.h"
PRAGMA_DISABLE_DEPRECATION_WARNINGS
#include "ClothingSimulationInteractor.h"
namespace {
}
void Gather_LhatBundledRuntime_ClothingSystemRuntimeInterface_0(TArray<FLhatNativeType>& Types)
{
    Types.Add({UClothingSimulationInteractor::StaticClass(), "ue.ClothingSystemRuntimeInterface", "ClothingSimulationInteractor"});
}
bool Register_LhatBundledRuntime_ClothingSystemRuntimeInterface_0(LhatProgram* P, FLhatBindings& B)
{
    return true;
}
PRAGMA_ENABLE_DEPRECATION_WARNINGS
