// Generated by GenerateNativeBindings.py; do not edit.
#include "LhatNativeBindings.h"
PRAGMA_DISABLE_DEPRECATION_WARNINGS
#include "Kismet/KismetMathLibrary.h"
namespace {
static void Call0(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 4) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    float Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    float Arg3{};
    if (!LhatUEBindings::Read(M, B, Args[3], Arg3)) return;
    const auto Result = UKismetMathLibrary::VInterpTo(Arg0, Arg1, Arg2, Arg3);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call1(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 4) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    float Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    float Arg3{};
    if (!LhatUEBindings::Read(M, B, Args[3], Arg3)) return;
    const auto Result = UKismetMathLibrary::VInterpTo_Constant(Arg0, Arg1, Arg2, Arg3);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call2(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    const auto Result = UKismetMathLibrary::Vector_Reciprocal(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call3(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    const auto Result = UKismetMathLibrary::GetReflectionVector(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call4(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    const auto Result = UKismetMathLibrary::MirrorVectorByNormal(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call5(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    float Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetMathLibrary::Vector_SnappedToGrid(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call6(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    float Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetMathLibrary::Vector_BoundedToCube(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call7(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    FVector Arg2{};
    if (!LhatUEBindings::ReadValue(M, B, Args[2], Arg2, "Vector")) return;
    const auto Result = UKismetMathLibrary::Vector_BoundedToBox(Arg0, Arg1, Arg2);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call8(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    const auto Result = UKismetMathLibrary::Vector_ProjectOnToNormal(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call9(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    const auto Result = UKismetMathLibrary::ProjectVectorOnToVector(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call10(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    FVector Arg2{};
    if (!LhatUEBindings::ReadValue(M, B, Args[2], Arg2, "Vector")) return;
    const auto Result = UKismetMathLibrary::ProjectPointOnToPlane(Arg0, Arg1, Arg2);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call11(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    const auto Result = UKismetMathLibrary::ProjectVectorOnToPlane(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call12(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    FVector Arg2{};
    if (!LhatUEBindings::ReadValue(M, B, Args[2], Arg2, "Vector")) return;
    const auto Result = UKismetMathLibrary::FindClosestPointOnSegment(Arg0, Arg1, Arg2);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call13(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    FVector Arg2{};
    if (!LhatUEBindings::ReadValue(M, B, Args[2], Arg2, "Vector")) return;
    const auto Result = UKismetMathLibrary::FindClosestPointOnLine(Arg0, Arg1, Arg2);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call14(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    FVector Arg2{};
    if (!LhatUEBindings::ReadValue(M, B, Args[2], Arg2, "Vector")) return;
    const auto Result = UKismetMathLibrary::GetPointDistanceToSegment(Arg0, Arg1, Arg2);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call15(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    FVector Arg2{};
    if (!LhatUEBindings::ReadValue(M, B, Args[2], Arg2, "Vector")) return;
    const auto Result = UKismetMathLibrary::GetPointDistanceToLine(Arg0, Arg1, Arg2);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call16(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetMathLibrary::RandomUnitVector();
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call17(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    const auto Result = UKismetMathLibrary::RandomPointInBoundingBox(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call18(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    float Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetMathLibrary::RandomUnitVectorInConeInRadians(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call19(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    float Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    float Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    const auto Result = UKismetMathLibrary::RandomUnitVectorInEllipticalConeInRadians(Arg0, Arg1, Arg2);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call20(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    float Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    float Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    float Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    const auto Result = UKismetMathLibrary::MakeRotator(Arg0, Arg1, Arg2);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Rotator")) *AnswerCount = 1;
}
static void Call21(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    const auto Result = UKismetMathLibrary::MakeRotFromX(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Rotator")) *AnswerCount = 1;
}
static void Call22(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    const auto Result = UKismetMathLibrary::MakeRotFromY(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Rotator")) *AnswerCount = 1;
}
static void Call23(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    const auto Result = UKismetMathLibrary::MakeRotFromZ(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Rotator")) *AnswerCount = 1;
}
static void Call24(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    const auto Result = UKismetMathLibrary::MakeRotFromXY(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Rotator")) *AnswerCount = 1;
}
static void Call25(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    const auto Result = UKismetMathLibrary::MakeRotFromXZ(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Rotator")) *AnswerCount = 1;
}
static void Call26(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    const auto Result = UKismetMathLibrary::MakeRotFromYX(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Rotator")) *AnswerCount = 1;
}
static void Call27(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    const auto Result = UKismetMathLibrary::MakeRotFromYZ(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Rotator")) *AnswerCount = 1;
}
static void Call28(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    const auto Result = UKismetMathLibrary::MakeRotFromZX(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Rotator")) *AnswerCount = 1;
}
static void Call29(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    const auto Result = UKismetMathLibrary::MakeRotFromZY(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Rotator")) *AnswerCount = 1;
}
static void Call30(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    FVector Arg2{};
    if (!LhatUEBindings::ReadValue(M, B, Args[2], Arg2, "Vector")) return;
    const auto Result = UKismetMathLibrary::MakeRotationFromAxes(Arg0, Arg1, Arg2);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Rotator")) *AnswerCount = 1;
}
static void Call31(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    const auto Result = UKismetMathLibrary::FindLookAtRotation(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Rotator")) *AnswerCount = 1;
}
static void Call32(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FTransform Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Transform")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    const auto Result = UKismetMathLibrary::FindRelativeLookAtRotation(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Rotator")) *AnswerCount = 1;
}
static void Call33(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FRotator Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Rotator")) return;
    FRotator Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Rotator")) return;
    float Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    const auto Result = UKismetMathLibrary::EqualEqual_RotatorRotator(Arg0, Arg1, Arg2);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call34(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FRotator Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Rotator")) return;
    FRotator Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Rotator")) return;
    float Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    const auto Result = UKismetMathLibrary::NotEqual_RotatorRotator(Arg0, Arg1, Arg2);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call35(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FRotator Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Rotator")) return;
    float Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetMathLibrary::Multiply_RotatorFloat(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Rotator")) *AnswerCount = 1;
}
static void Call36(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FRotator Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Rotator")) return;
    int32 Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetMathLibrary::Multiply_RotatorInt(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Rotator")) *AnswerCount = 1;
}
static void Call37(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FRotator Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Rotator")) return;
    FRotator Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Rotator")) return;
    const auto Result = UKismetMathLibrary::ComposeRotators(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Rotator")) *AnswerCount = 1;
}
static void Call38(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FRotator Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Rotator")) return;
    const auto Result = UKismetMathLibrary::NegateRotator(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Rotator")) *AnswerCount = 1;
}
static void Call39(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FRotator Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Rotator")) return;
    const auto Result = UKismetMathLibrary::GetForwardVector(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call40(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FRotator Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Rotator")) return;
    const auto Result = UKismetMathLibrary::GetRightVector(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call41(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FRotator Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Rotator")) return;
    const auto Result = UKismetMathLibrary::GetUpVector(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call42(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FRotator Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Rotator")) return;
    const auto Result = UKismetMathLibrary::Conv_RotatorToVector(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call43(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FRotator Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Rotator")) return;
    const auto Result = UKismetMathLibrary::Conv_RotatorToTransform(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Transform")) *AnswerCount = 1;
}
static void Call44(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    bool Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetMathLibrary::RandomRotator(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Rotator")) *AnswerCount = 1;
}
static void Call45(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 4) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FRotator Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Rotator")) return;
    FRotator Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Rotator")) return;
    float Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    bool Arg3{};
    if (!LhatUEBindings::Read(M, B, Args[3], Arg3)) return;
    const auto Result = UKismetMathLibrary::RLerp(Arg0, Arg1, Arg2, Arg3);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Rotator")) *AnswerCount = 1;
}
static void Call46(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FRotator Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Rotator")) return;
    FRotator Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Rotator")) return;
    const auto Result = UKismetMathLibrary::NormalizedDeltaRotator(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Rotator")) *AnswerCount = 1;
}
static void Call47(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    float Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetMathLibrary::ClampAxis(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call48(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    float Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetMathLibrary::NormalizeAxis(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call49(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetMathLibrary::Quat_Identity();
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Quat")) *AnswerCount = 1;
}
static void Call50(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FQuat Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Quat")) return;
    FQuat Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Quat")) return;
    float Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    const auto Result = UKismetMathLibrary::EqualEqual_QuatQuat(Arg0, Arg1, Arg2);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call51(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FQuat Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Quat")) return;
    FQuat Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Quat")) return;
    float Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    const auto Result = UKismetMathLibrary::NotEqual_QuatQuat(Arg0, Arg1, Arg2);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call52(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FQuat Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Quat")) return;
    FQuat Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Quat")) return;
    const auto Result = UKismetMathLibrary::Add_QuatQuat(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Quat")) *AnswerCount = 1;
}
static void Call53(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FQuat Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Quat")) return;
    FQuat Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Quat")) return;
    const auto Result = UKismetMathLibrary::Subtract_QuatQuat(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Quat")) *AnswerCount = 1;
}
static void Call54(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 4) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    float Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    float Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    float Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    float Arg3{};
    if (!LhatUEBindings::Read(M, B, Args[3], Arg3)) return;
    const auto Result = UKismetMathLibrary::MakeQuat(Arg0, Arg1, Arg2, Arg3);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Quat")) *AnswerCount = 1;
}
static void Call55(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FQuat Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Quat")) return;
    FQuat Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Quat")) return;
    const auto Result = UKismetMathLibrary::Multiply_QuatQuat(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Quat")) *AnswerCount = 1;
}
static void Call56(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FQuat Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Quat")) return;
    float Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetMathLibrary::Quat_IsIdentity(Arg0, Arg1);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call57(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FQuat Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Quat")) return;
    const auto Result = UKismetMathLibrary::Quat_IsNormalized(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call58(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FQuat Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Quat")) return;
    const auto Result = UKismetMathLibrary::Quat_IsFinite(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call59(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FQuat Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Quat")) return;
    const auto Result = UKismetMathLibrary::Quat_IsNonFinite(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call60(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FQuat Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Quat")) return;
    FQuat Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Quat")) return;
    const auto Result = UKismetMathLibrary::Quat_AngularDistance(Arg0, Arg1);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call61(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FQuat Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Quat")) return;
    FQuat Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Quat")) return;
    const auto Result = UKismetMathLibrary::Quat_GetShortestArcWith(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Quat")) *AnswerCount = 1;
}
static void Call62(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FQuat Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Quat")) return;
    const auto Result = UKismetMathLibrary::Quat_Euler(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call63(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FQuat Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Quat")) return;
    const auto Result = UKismetMathLibrary::Quat_Exp(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Quat")) *AnswerCount = 1;
}
static void Call64(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FQuat Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Quat")) return;
    const auto Result = UKismetMathLibrary::Quat_GetAngle(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call65(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FQuat Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Quat")) return;
    const auto Result = UKismetMathLibrary::Quat_GetAxisX(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call66(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FQuat Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Quat")) return;
    const auto Result = UKismetMathLibrary::Quat_GetAxisY(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call67(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FQuat Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Quat")) return;
    const auto Result = UKismetMathLibrary::Quat_GetAxisZ(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call68(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FQuat Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Quat")) return;
    const auto Result = UKismetMathLibrary::Quat_VectorForward(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call69(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FQuat Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Quat")) return;
    const auto Result = UKismetMathLibrary::Quat_VectorRight(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call70(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FQuat Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Quat")) return;
    const auto Result = UKismetMathLibrary::Quat_VectorUp(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call71(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FQuat Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Quat")) return;
    float Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetMathLibrary::Quat_Normalized(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Quat")) *AnswerCount = 1;
}
static void Call72(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FQuat Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Quat")) return;
    const auto Result = UKismetMathLibrary::Quat_GetRotationAxis(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call73(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FQuat Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Quat")) return;
    const auto Result = UKismetMathLibrary::Quat_Inversed(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Quat")) *AnswerCount = 1;
}
static void Call74(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FQuat Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Quat")) return;
    const auto Result = UKismetMathLibrary::Quat_Log(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Quat")) *AnswerCount = 1;
}
static void Call75(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    const auto Result = UKismetMathLibrary::Quat_MakeFromEuler(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Quat")) *AnswerCount = 1;
}
static void Call76(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FQuat Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Quat")) return;
    const auto Result = UKismetMathLibrary::Quat_Rotator(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Rotator")) *AnswerCount = 1;
}
static void Call77(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FRotator Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Rotator")) return;
    const auto Result = UKismetMathLibrary::Conv_RotatorToQuaternion(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Quat")) *AnswerCount = 1;
}
static void Call78(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FQuat Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Quat")) return;
    const auto Result = UKismetMathLibrary::Quat_ToRotationVector(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call79(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    const auto Result = UKismetMathLibrary::Quat_MakeFromRotationVector(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Quat")) *AnswerCount = 1;
}
}
void Gather_LhatBundledRuntime_Engine_6(TArray<FLhatNativeType>& Types)
{
}
bool Register_LhatBundledRuntime_Engine_6(LhatProgram* P, FLhatBindings& B)
{
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "VInterpTo", "f^ue.Vector, ue.Vector, number^, number^ -> ue.Vector;", Call0, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "VInterpTo_Constant", "f^ue.Vector, ue.Vector, number^, number^ -> ue.Vector;", Call1, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector_Reciprocal", "f^ue.Vector -> ue.Vector;", Call2, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "GetReflectionVector", "f^ue.Vector, ue.Vector -> ue.Vector;", Call3, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "MirrorVectorByNormal", "f^ue.Vector, ue.Vector -> ue.Vector;", Call4, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector_SnappedToGrid", "f^ue.Vector, number^ -> ue.Vector;", Call5, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector_BoundedToCube", "f^ue.Vector, number^ -> ue.Vector;", Call6, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector_BoundedToBox", "f^ue.Vector, ue.Vector, ue.Vector -> ue.Vector;", Call7, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector_ProjectOnToNormal", "f^ue.Vector, ue.Vector -> ue.Vector;", Call8, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "ProjectVectorOnToVector", "f^ue.Vector, ue.Vector -> ue.Vector;", Call9, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "ProjectPointOnToPlane", "f^ue.Vector, ue.Vector, ue.Vector -> ue.Vector;", Call10, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "ProjectVectorOnToPlane", "f^ue.Vector, ue.Vector -> ue.Vector;", Call11, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "FindClosestPointOnSegment", "f^ue.Vector, ue.Vector, ue.Vector -> ue.Vector;", Call12, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "FindClosestPointOnLine", "f^ue.Vector, ue.Vector, ue.Vector -> ue.Vector;", Call13, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "GetPointDistanceToSegment", "f^ue.Vector, ue.Vector, ue.Vector -> number^;", Call14, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "GetPointDistanceToLine", "f^ue.Vector, ue.Vector, ue.Vector -> number^;", Call15, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "RandomUnitVector", "f^ -> ue.Vector;", Call16, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "RandomPointInBoundingBox", "f^ue.Vector, ue.Vector -> ue.Vector;", Call17, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "RandomUnitVectorInConeInRadians", "f^ue.Vector, number^ -> ue.Vector;", Call18, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "RandomUnitVectorInEllipticalConeInRadians", "f^ue.Vector, number^, number^ -> ue.Vector;", Call19, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "MakeRotator", "f^number^, number^, number^ -> ue.Rotator;", Call20, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "MakeRotFromX", "f^ue.Vector -> ue.Rotator;", Call21, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "MakeRotFromY", "f^ue.Vector -> ue.Rotator;", Call22, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "MakeRotFromZ", "f^ue.Vector -> ue.Rotator;", Call23, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "MakeRotFromXY", "f^ue.Vector, ue.Vector -> ue.Rotator;", Call24, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "MakeRotFromXZ", "f^ue.Vector, ue.Vector -> ue.Rotator;", Call25, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "MakeRotFromYX", "f^ue.Vector, ue.Vector -> ue.Rotator;", Call26, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "MakeRotFromYZ", "f^ue.Vector, ue.Vector -> ue.Rotator;", Call27, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "MakeRotFromZX", "f^ue.Vector, ue.Vector -> ue.Rotator;", Call28, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "MakeRotFromZY", "f^ue.Vector, ue.Vector -> ue.Rotator;", Call29, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "MakeRotationFromAxes", "f^ue.Vector, ue.Vector, ue.Vector -> ue.Rotator;", Call30, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "FindLookAtRotation", "f^ue.Vector, ue.Vector -> ue.Rotator;", Call31, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "FindRelativeLookAtRotation", "f^ue.Transform, ue.Vector -> ue.Rotator;", Call32, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "EqualEqual_RotatorRotator", "f^ue.Rotator, ue.Rotator, number^ -> bool^;", Call33, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "NotEqual_RotatorRotator", "f^ue.Rotator, ue.Rotator, number^ -> bool^;", Call34, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Multiply_RotatorFloat", "f^ue.Rotator, number^ -> ue.Rotator;", Call35, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Multiply_RotatorInt", "f^ue.Rotator, number^ -> ue.Rotator;", Call36, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "ComposeRotators", "f^ue.Rotator, ue.Rotator -> ue.Rotator;", Call37, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "NegateRotator", "f^ue.Rotator -> ue.Rotator;", Call38, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "GetForwardVector", "f^ue.Rotator -> ue.Vector;", Call39, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "GetRightVector", "f^ue.Rotator -> ue.Vector;", Call40, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "GetUpVector", "f^ue.Rotator -> ue.Vector;", Call41, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Conv_RotatorToVector", "f^ue.Rotator -> ue.Vector;", Call42, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Conv_RotatorToTransform", "f^ue.Rotator -> ue.Transform;", Call43, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "RandomRotator", "f^bool^ -> ue.Rotator;", Call44, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "RLerp", "f^ue.Rotator, ue.Rotator, number^, bool^ -> ue.Rotator;", Call45, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "NormalizedDeltaRotator", "f^ue.Rotator, ue.Rotator -> ue.Rotator;", Call46, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "ClampAxis", "f^number^ -> number^;", Call47, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "NormalizeAxis", "f^number^ -> number^;", Call48, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Quat_Identity", "f^ -> ue.Quat;", Call49, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "EqualEqual_QuatQuat", "f^ue.Quat, ue.Quat, number^ -> bool^;", Call50, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "NotEqual_QuatQuat", "f^ue.Quat, ue.Quat, number^ -> bool^;", Call51, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Add_QuatQuat", "f^ue.Quat, ue.Quat -> ue.Quat;", Call52, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Subtract_QuatQuat", "f^ue.Quat, ue.Quat -> ue.Quat;", Call53, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "MakeQuat", "f^number^, number^, number^, number^ -> ue.Quat;", Call54, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Multiply_QuatQuat", "f^ue.Quat, ue.Quat -> ue.Quat;", Call55, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Quat_IsIdentity", "f^ue.Quat, number^ -> bool^;", Call56, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Quat_IsNormalized", "f^ue.Quat -> bool^;", Call57, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Quat_IsFinite", "f^ue.Quat -> bool^;", Call58, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Quat_IsNonFinite", "f^ue.Quat -> bool^;", Call59, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Quat_AngularDistance", "f^ue.Quat, ue.Quat -> number^;", Call60, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Quat_GetShortestArcWith", "f^ue.Quat, ue.Quat -> ue.Quat;", Call61, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Quat_Euler", "f^ue.Quat -> ue.Vector;", Call62, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Quat_Exp", "f^ue.Quat -> ue.Quat;", Call63, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Quat_GetAngle", "f^ue.Quat -> number^;", Call64, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Quat_GetAxisX", "f^ue.Quat -> ue.Vector;", Call65, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Quat_GetAxisY", "f^ue.Quat -> ue.Vector;", Call66, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Quat_GetAxisZ", "f^ue.Quat -> ue.Vector;", Call67, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Quat_VectorForward", "f^ue.Quat -> ue.Vector;", Call68, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Quat_VectorRight", "f^ue.Quat -> ue.Vector;", Call69, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Quat_VectorUp", "f^ue.Quat -> ue.Vector;", Call70, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Quat_Normalized", "f^ue.Quat, number^ -> ue.Quat;", Call71, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Quat_GetRotationAxis", "f^ue.Quat -> ue.Vector;", Call72, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Quat_Inversed", "f^ue.Quat -> ue.Quat;", Call73, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Quat_Log", "f^ue.Quat -> ue.Quat;", Call74, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Quat_MakeFromEuler", "f^ue.Vector -> ue.Quat;", Call75, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Quat_Rotator", "f^ue.Quat -> ue.Rotator;", Call76, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Conv_RotatorToQuaternion", "f^ue.Rotator -> ue.Quat;", Call77, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Quat_ToRotationVector", "f^ue.Quat -> ue.Vector;", Call78, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Quat_MakeFromRotationVector", "f^ue.Vector -> ue.Quat;", Call79, &B)) return false;
    return true;
}
PRAGMA_ENABLE_DEPRECATION_WARNINGS
