// Generated by GenerateNativeBindings.py; do not edit.
#include "LhatNativeBindings.h"
PRAGMA_DISABLE_DEPRECATION_WARNINGS
#include "Camera/CameraShakeSourceComponent.h"
#include "Components/PrimitiveComponent.h"
#include "Components/SceneComponent.h"
#include "GameFramework/Actor.h"
#include "GameFramework/ForceFeedbackEffect.h"
#include "GameFramework/HUD.h"
#include "GameFramework/PlayerController.h"
#include "GameFramework/TouchInterface.h"
#include "Materials/MaterialInstanceDynamic.h"
#include "Materials/MaterialInterface.h"
namespace {
static void Call0(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APlayerController*>(B.ReadObject(M, Args[0], APlayerController::StaticClass()));
    if (!Self) return;
    float Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    Self->SetDeprecatedInputRollScale(Arg0);
}
static void Call1(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APlayerController*>(B.ReadObject(M, Args[0], APlayerController::StaticClass()));
    if (!Self) return;
    bool Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    Self->SetMotionControlsEnabled(Arg0);
}
static void Call2(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APlayerController*>(B.ReadObject(M, Args[0], APlayerController::StaticClass()));
    if (!Self) return;
    int32 Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    int32 Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg1)) return;
    Self->SetMouseLocation(Arg0, Arg1);
}
static void Call3(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APlayerController*>(B.ReadObject(M, Args[0], APlayerController::StaticClass()));
    if (!Self) return;
    const auto Result = Self->GetHUD();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call4(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APlayerController*>(B.ReadObject(M, Args[0], APlayerController::StaticClass()));
    if (!Self) return;
    UCameraShakeSourceComponent* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    bool Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg1)) return;
    Self->ClientStopCameraShakesFromSource(Arg0, Arg1);
}
static void Call5(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 6) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APlayerController*>(B.ReadObject(M, Args[0], APlayerController::StaticClass()));
    if (!Self) return;
    UForceFeedbackEffect* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    FName Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg1)) return;
    bool Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[3], Arg2)) return;
    bool Arg3{};
    if (!LhatUEBindings::Read(M, B, Args[4], Arg3)) return;
    bool Arg4{};
    if (!LhatUEBindings::Read(M, B, Args[5], Arg4)) return;
    Self->K2_ClientPlayForceFeedback(Arg0, Arg1, Arg2, Arg3, Arg4);
}
static void Call6(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APlayerController*>(B.ReadObject(M, Args[0], APlayerController::StaticClass()));
    if (!Self) return;
    bool Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    Self->SetDisableHaptics(Arg0);
}
static void Call7(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APlayerController*>(B.ReadObject(M, Args[0], APlayerController::StaticClass()));
    if (!Self) return;
    FColor Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg0, "Color")) return;
    Self->SetControllerLightColor(Arg0);
}
static void Call8(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APlayerController*>(B.ReadObject(M, Args[0], APlayerController::StaticClass()));
    if (!Self) return;
    Self->ResetControllerLightColor();
}
static void Call9(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APlayerController*>(B.ReadObject(M, Args[0], APlayerController::StaticClass()));
    if (!Self) return;
    float Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    float Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg1)) return;
    Self->SetControllerDeadZones(Arg0, Arg1);
}
static void Call10(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APlayerController*>(B.ReadObject(M, Args[0], APlayerController::StaticClass()));
    if (!Self) return;
    Self->ResetControllerDeadZones();
}
static void Call11(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APlayerController*>(B.ReadObject(M, Args[0], APlayerController::StaticClass()));
    if (!Self) return;
    float Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    float Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg1)) return;
    Self->SetControllerTriggerReleaseThresholds(Arg0, Arg1);
}
static void Call12(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APlayerController*>(B.ReadObject(M, Args[0], APlayerController::StaticClass()));
    if (!Self) return;
    Self->ResetControllerTriggerReleaseThresholds();
}
static void Call13(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APlayerController*>(B.ReadObject(M, Args[0], APlayerController::StaticClass()));
    if (!Self) return;
    bool Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    Self->SetControllerGyroAutoCalibration(Arg0);
}
static void Call14(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APlayerController*>(B.ReadObject(M, Args[0], APlayerController::StaticClass()));
    if (!Self) return;
    float Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    Self->AddPitchInput(Arg0);
}
static void Call15(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APlayerController*>(B.ReadObject(M, Args[0], APlayerController::StaticClass()));
    if (!Self) return;
    float Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    Self->AddYawInput(Arg0);
}
static void Call16(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APlayerController*>(B.ReadObject(M, Args[0], APlayerController::StaticClass()));
    if (!Self) return;
    float Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    Self->AddRollInput(Arg0);
}
static void Call17(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APlayerController*>(B.ReadObject(M, Args[0], APlayerController::StaticClass()));
    if (!Self) return;
    UTouchInterface* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    Self->ActivateTouchInterface(Arg0);
}
static void Call18(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APlayerController*>(B.ReadObject(M, Args[0], APlayerController::StaticClass()));
    if (!Self) return;
    bool Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    Self->SetVirtualJoystickVisibility(Arg0);
}
static void Call19(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 4) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APlayerController*>(B.ReadObject(M, Args[0], APlayerController::StaticClass()));
    if (!Self) return;
    USceneComponent* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[2], Arg1, "Vector")) return;
    FRotator Arg2{};
    if (!LhatUEBindings::ReadValue(M, B, Args[3], Arg2, "Rotator")) return;
    Self->SetAudioListenerOverride(Arg0, Arg1, Arg2);
}
static void Call20(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APlayerController*>(B.ReadObject(M, Args[0], APlayerController::StaticClass()));
    if (!Self) return;
    Self->ClearAudioListenerOverride();
}
static void Call21(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APlayerController*>(B.ReadObject(M, Args[0], APlayerController::StaticClass()));
    if (!Self) return;
    USceneComponent* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[2], Arg1, "Vector")) return;
    Self->SetAudioListenerAttenuationOverride(Arg0, Arg1);
}
static void Call22(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APlayerController*>(B.ReadObject(M, Args[0], APlayerController::StaticClass()));
    if (!Self) return;
    Self->ClearAudioListenerAttenuationOverride();
}
static void Call23(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APlayerController*>(B.ReadObject(M, Args[0], APlayerController::StaticClass()));
    if (!Self) return;
    const auto Result = Self->CanRestartPlayer();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call24(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 6) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APlayerController*>(B.ReadObject(M, Args[0], APlayerController::StaticClass()));
    if (!Self) return;
    bool Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    bool Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg1)) return;
    bool Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[3], Arg2)) return;
    bool Arg3{};
    if (!LhatUEBindings::Read(M, B, Args[4], Arg3)) return;
    bool Arg4{};
    if (!LhatUEBindings::Read(M, B, Args[5], Arg4)) return;
    Self->SetCinematicMode(Arg0, Arg1, Arg2, Arg3, Arg4);
}
static void Call25(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APlayerController*>(B.ReadObject(M, Args[0], APlayerController::StaticClass()));
    if (!Self) return;
    const auto Result = Self->IsPrimaryPlayer();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call26(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APlayerController*>(B.ReadObject(M, Args[0], APlayerController::StaticClass()));
    if (!Self) return;
    const auto Result = Self->GetFocalLocation();
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call27(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    bool Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    Self->SetGenerateOverlapEvents(Arg0);
}
static void Call28(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 4) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    bool Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    bool Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg1)) return;
    bool Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[3], Arg2)) return;
    Self->SetLightingChannels(Arg0, Arg1, Arg2);
}
static void Call29(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    Self->InvalidateLumenSurfaceCache();
}
static void Call30(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    float Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    const auto Result = Self->WasRecentlyRendered(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call31(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    AActor* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    bool Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg1)) return;
    Self->IgnoreActorWhenMoving(Arg0, Arg1);
}
static void Call32(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    Self->ClearMoveIgnoreActors();
}
static void Call33(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    UPrimitiveComponent* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    bool Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg1)) return;
    Self->IgnoreComponentWhenMoving(Arg0, Arg1);
}
static void Call34(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    FName Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    const auto Result = Self->GetCustomPrimitiveDataIndexForScalarParameter(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call35(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    FName Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    const auto Result = Self->GetCustomPrimitiveDataIndexForVectorParameter(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call36(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    FName Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    float Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg1)) return;
    Self->SetScalarParameterForCustomPrimitiveData(Arg0, Arg1);
}
static void Call37(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    int32 Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    float Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg1)) return;
    Self->SetCustomPrimitiveDataFloat(Arg0, Arg1);
}
static void Call38(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    int32 Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    FVector2D Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[2], Arg1, "Vector2D")) return;
    Self->SetCustomPrimitiveDataVector2(Arg0, Arg1);
}
static void Call39(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    int32 Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[2], Arg1, "Vector")) return;
    Self->SetCustomPrimitiveDataVector3(Arg0, Arg1);
}
static void Call40(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    FName Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    float Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg1)) return;
    Self->SetScalarParameterForDefaultCustomPrimitiveData(Arg0, Arg1);
}
static void Call41(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    int32 Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    float Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg1)) return;
    Self->SetDefaultCustomPrimitiveDataFloat(Arg0, Arg1);
}
static void Call42(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    int32 Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    FVector2D Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[2], Arg1, "Vector2D")) return;
    Self->SetDefaultCustomPrimitiveDataVector2(Arg0, Arg1);
}
static void Call43(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    int32 Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[2], Arg1, "Vector")) return;
    Self->SetDefaultCustomPrimitiveDataVector3(Arg0, Arg1);
}
static void Call44(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    Self->SetupDefaultCustomPrimitiveDataFromMaterials();
}
static void Call45(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    UPrimitiveComponent* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    const auto Result = Self->IsOverlappingComponent(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call46(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    AActor* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    const auto Result = Self->IsOverlappingActor(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call47(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    float Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    Self->SetBoundsScale(Arg0);
}
static void Call48(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    int32 Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    const auto Result = Self->GetMaterial(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call49(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    FName Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    const auto Result = Self->GetMaterialIndex(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call50(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    FName Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    const auto Result = Self->IsMaterialSlotNameValid(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call51(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    FName Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    const auto Result = Self->GetMaterialByName(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call52(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    int32 Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    UMaterialInterface* Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg1)) return;
    Self->SetMaterial(Arg0, Arg1);
}
static void Call53(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    FName Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    UMaterialInterface* Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg1)) return;
    Self->SetMaterialByName(Arg0, Arg1);
}
static void Call54(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    int32 Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    const auto Result = Self->CreateAndSetMaterialInstanceDynamic(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call55(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    int32 Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    UMaterialInterface* Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg1)) return;
    const auto Result = Self->CreateAndSetMaterialInstanceDynamicFromMaterial(Arg0, Arg1);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call56(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 4) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    int32 Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    UMaterialInterface* Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg1)) return;
    FName Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[3], Arg2)) return;
    const auto Result = Self->CreateDynamicMaterialInstance(Arg0, Arg1, Arg2);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call57(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    bool Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    Self->SetSimulatePhysics(Arg0);
}
static void Call58(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    bool Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    Self->SetStaticWhenNotMoveable(Arg0);
}
static void Call59(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 4) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg0, "Vector")) return;
    FName Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg1)) return;
    bool Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[3], Arg2)) return;
    Self->AddImpulse(Arg0, Arg1, Arg2);
}
static void Call60(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 4) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg0, "Vector")) return;
    FName Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg1)) return;
    bool Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[3], Arg2)) return;
    Self->AddAngularImpulseInRadians(Arg0, Arg1, Arg2);
}
static void Call61(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 4) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[2], Arg1, "Vector")) return;
    FName Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[3], Arg2)) return;
    Self->AddImpulseAtLocation(Arg0, Arg1, Arg2);
}
static void Call62(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 4) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[2], Arg1, "Vector")) return;
    FName Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[3], Arg2)) return;
    Self->AddVelocityChangeImpulseAtLocation(Arg0, Arg1, Arg2);
}
static void Call63(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 4) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg0, "Vector")) return;
    FName Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg1)) return;
    bool Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[3], Arg2)) return;
    Self->AddForce(Arg0, Arg1, Arg2);
}
static void Call64(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 4) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[2], Arg1, "Vector")) return;
    FName Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[3], Arg2)) return;
    Self->AddForceAtLocation(Arg0, Arg1, Arg2);
}
static void Call65(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 4) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[2], Arg1, "Vector")) return;
    FName Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[3], Arg2)) return;
    Self->AddForceAtLocationLocal(Arg0, Arg1, Arg2);
}
static void Call66(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 4) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg0, "Vector")) return;
    FName Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg1)) return;
    bool Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[3], Arg2)) return;
    Self->AddTorqueInRadians(Arg0, Arg1, Arg2);
}
static void Call67(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 4) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg0, "Vector")) return;
    bool Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg1)) return;
    FName Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[3], Arg2)) return;
    Self->SetPhysicsLinearVelocity(Arg0, Arg1, Arg2);
}
static void Call68(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    FName Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    const auto Result = Self->GetPhysicsLinearVelocity(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call69(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg0, "Vector")) return;
    FName Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg1)) return;
    const auto Result = Self->GetPhysicsLinearVelocityAtPoint(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call70(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg0, "Vector")) return;
    bool Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg1)) return;
    Self->SetAllPhysicsLinearVelocity(Arg0, Arg1);
}
static void Call71(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 4) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg0, "Vector")) return;
    bool Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg1)) return;
    FName Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[3], Arg2)) return;
    Self->SetPhysicsAngularVelocityInRadians(Arg0, Arg1, Arg2);
}
static void Call72(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 4) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    float Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    bool Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg1)) return;
    FName Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[3], Arg2)) return;
    Self->SetPhysicsMaxAngularVelocityInRadians(Arg0, Arg1, Arg2);
}
static void Call73(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    FName Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    const auto Result = Self->GetPhysicsAngularVelocityInRadians(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call74(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    FName Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    const auto Result = Self->GetCenterOfMass(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call75(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg0, "Vector")) return;
    FName Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg1)) return;
    Self->SetCenterOfMass(Arg0, Arg1);
}
static void Call76(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    FName Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    Self->WakeRigidBody(Arg0);
}
static void Call77(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    FName Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    Self->PutRigidBodyToSleep(Arg0);
}
static void Call78(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    bool Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    Self->SetNotifyRigidBodyCollision(Arg0);
}
static void Call79(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPrimitiveComponent*>(B.ReadObject(M, Args[0], UPrimitiveComponent::StaticClass()));
    if (!Self) return;
    bool Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    Self->SetOwnerNoSee(Arg0);
}
}
void Gather_LhatBundledRuntime_Engine_11(TArray<FLhatNativeType>& Types)
{
}
bool Register_LhatBundledRuntime_Engine_11(LhatProgram* P, FLhatBindings& B)
{
    if (!lhat_register_member(P, "ue.Engine", "PlayerController", "SetDeprecatedInputRollScale", "p^self^, number^;", Call0, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PlayerController", "SetMotionControlsEnabled", "p^self^, bool^;", Call1, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PlayerController", "SetMouseLocation", "p^self^, number^, number^;", Call2, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PlayerController", "GetHUD", "f^self^ -> ue.Engine.HUD|nil^;", Call3, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PlayerController", "ClientStopCameraShakesFromSource", "p^self^, ue.Engine.CameraShakeSourceComponent|nil^, bool^;", Call4, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PlayerController", "K2_ClientPlayForceFeedback", "p^self^, ue.Engine.ForceFeedbackEffect|nil^, string^, bool^, bool^, bool^;", Call5, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PlayerController", "SetDisableHaptics", "p^self^, bool^;", Call6, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PlayerController", "SetControllerLightColor", "p^self^, ue.Color;", Call7, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PlayerController", "ResetControllerLightColor", "p^self^;", Call8, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PlayerController", "SetControllerDeadZones", "p^self^, number^, number^;", Call9, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PlayerController", "ResetControllerDeadZones", "p^self^;", Call10, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PlayerController", "SetControllerTriggerReleaseThresholds", "p^self^, number^, number^;", Call11, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PlayerController", "ResetControllerTriggerReleaseThresholds", "p^self^;", Call12, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PlayerController", "SetControllerGyroAutoCalibration", "p^self^, bool^;", Call13, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PlayerController", "AddPitchInput", "p^self^, number^;", Call14, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PlayerController", "AddYawInput", "p^self^, number^;", Call15, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PlayerController", "AddRollInput", "p^self^, number^;", Call16, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PlayerController", "ActivateTouchInterface", "p^self^, ue.Engine.TouchInterface|nil^;", Call17, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PlayerController", "SetVirtualJoystickVisibility", "p^self^, bool^;", Call18, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PlayerController", "SetAudioListenerOverride", "p^self^, ue.Engine.SceneComponent|nil^, ue.Vector, ue.Rotator;", Call19, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PlayerController", "ClearAudioListenerOverride", "p^self^;", Call20, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PlayerController", "SetAudioListenerAttenuationOverride", "p^self^, ue.Engine.SceneComponent|nil^, ue.Vector;", Call21, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PlayerController", "ClearAudioListenerAttenuationOverride", "p^self^;", Call22, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PlayerController", "CanRestartPlayer", "p^self^ -> bool^;", Call23, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PlayerController", "SetCinematicMode", "p^self^, bool^, bool^, bool^, bool^, bool^;", Call24, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PlayerController", "IsPrimaryPlayer", "f^self^ -> bool^;", Call25, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PlayerController", "GetFocalLocation", "f^self^ -> ue.Vector;", Call26, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "SetGenerateOverlapEvents", "p^self^, bool^;", Call27, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "SetLightingChannels", "p^self^, bool^, bool^, bool^;", Call28, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "InvalidateLumenSurfaceCache", "p^self^;", Call29, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "WasRecentlyRendered", "f^self^, number^ -> bool^;", Call30, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "IgnoreActorWhenMoving", "p^self^, ue.Actor|nil^, bool^;", Call31, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "ClearMoveIgnoreActors", "p^self^;", Call32, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "IgnoreComponentWhenMoving", "p^self^, ue.Engine.PrimitiveComponent|nil^, bool^;", Call33, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "GetCustomPrimitiveDataIndexForScalarParameter", "f^self^, string^ -> number^;", Call34, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "GetCustomPrimitiveDataIndexForVectorParameter", "f^self^, string^ -> number^;", Call35, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "SetScalarParameterForCustomPrimitiveData", "p^self^, string^, number^;", Call36, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "SetCustomPrimitiveDataFloat", "p^self^, number^, number^;", Call37, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "SetCustomPrimitiveDataVector2", "p^self^, number^, ue.Vector2D;", Call38, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "SetCustomPrimitiveDataVector3", "p^self^, number^, ue.Vector;", Call39, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "SetScalarParameterForDefaultCustomPrimitiveData", "p^self^, string^, number^;", Call40, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "SetDefaultCustomPrimitiveDataFloat", "p^self^, number^, number^;", Call41, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "SetDefaultCustomPrimitiveDataVector2", "p^self^, number^, ue.Vector2D;", Call42, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "SetDefaultCustomPrimitiveDataVector3", "p^self^, number^, ue.Vector;", Call43, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "SetupDefaultCustomPrimitiveDataFromMaterials", "p^self^;", Call44, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "IsOverlappingComponent", "f^self^, ue.Engine.PrimitiveComponent|nil^ -> bool^;", Call45, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "IsOverlappingActor", "f^self^, ue.Actor|nil^ -> bool^;", Call46, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "SetBoundsScale", "p^self^, number^;", Call47, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "GetMaterial", "f^self^, number^ -> ue.Engine.MaterialInterface|nil^;", Call48, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "GetMaterialIndex", "f^self^, string^ -> number^;", Call49, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "IsMaterialSlotNameValid", "f^self^, string^ -> bool^;", Call50, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "GetMaterialByName", "f^self^, string^ -> ue.Engine.MaterialInterface|nil^;", Call51, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "SetMaterial", "p^self^, number^, ue.Engine.MaterialInterface|nil^;", Call52, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "SetMaterialByName", "p^self^, string^, ue.Engine.MaterialInterface|nil^;", Call53, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "CreateAndSetMaterialInstanceDynamic", "p^self^, number^ -> ue.Engine.MaterialInstanceDynamic|nil^;", Call54, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "CreateAndSetMaterialInstanceDynamicFromMaterial", "p^self^, number^, ue.Engine.MaterialInterface|nil^ -> ue.Engine.MaterialInstanceDynamic|nil^;", Call55, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "CreateDynamicMaterialInstance", "p^self^, number^, ue.Engine.MaterialInterface|nil^, string^ -> ue.Engine.MaterialInstanceDynamic|nil^;", Call56, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "SetSimulatePhysics", "p^self^, bool^;", Call57, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "SetStaticWhenNotMoveable", "p^self^, bool^;", Call58, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "AddImpulse", "p^self^, ue.Vector, string^, bool^;", Call59, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "AddAngularImpulseInRadians", "p^self^, ue.Vector, string^, bool^;", Call60, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "AddImpulseAtLocation", "p^self^, ue.Vector, ue.Vector, string^;", Call61, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "AddVelocityChangeImpulseAtLocation", "p^self^, ue.Vector, ue.Vector, string^;", Call62, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "AddForce", "p^self^, ue.Vector, string^, bool^;", Call63, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "AddForceAtLocation", "p^self^, ue.Vector, ue.Vector, string^;", Call64, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "AddForceAtLocationLocal", "p^self^, ue.Vector, ue.Vector, string^;", Call65, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "AddTorqueInRadians", "p^self^, ue.Vector, string^, bool^;", Call66, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "SetPhysicsLinearVelocity", "p^self^, ue.Vector, bool^, string^;", Call67, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "GetPhysicsLinearVelocity", "p^self^, string^ -> ue.Vector;", Call68, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "GetPhysicsLinearVelocityAtPoint", "p^self^, ue.Vector, string^ -> ue.Vector;", Call69, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "SetAllPhysicsLinearVelocity", "p^self^, ue.Vector, bool^;", Call70, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "SetPhysicsAngularVelocityInRadians", "p^self^, ue.Vector, bool^, string^;", Call71, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "SetPhysicsMaxAngularVelocityInRadians", "p^self^, number^, bool^, string^;", Call72, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "GetPhysicsAngularVelocityInRadians", "f^self^, string^ -> ue.Vector;", Call73, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "GetCenterOfMass", "f^self^, string^ -> ue.Vector;", Call74, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "SetCenterOfMass", "p^self^, ue.Vector, string^;", Call75, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "WakeRigidBody", "p^self^, string^;", Call76, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "PutRigidBodyToSleep", "p^self^, string^;", Call77, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "SetNotifyRigidBodyCollision", "p^self^, bool^;", Call78, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PrimitiveComponent", "SetOwnerNoSee", "p^self^, bool^;", Call79, &B)) return false;
    return true;
}
PRAGMA_ENABLE_DEPRECATION_WARNINGS
