// Generated by GenerateBundledBindings.py; do not edit.
#include "LhatNativeBindings.h"
void Gather_LhatBundledRuntime_ClothingSystemRuntimeInterface_0(TArray<FLhatNativeType>&);
bool Register_LhatBundledRuntime_ClothingSystemRuntimeInterface_0(LhatProgram*, FLhatBindings&);
void Gather_LhatBundledRuntime_Engine_0(TArray<FLhatNativeType>&);
bool Register_LhatBundledRuntime_Engine_0(LhatProgram*, FLhatBindings&);
void Gather_LhatBundledRuntime_Engine_1(TArray<FLhatNativeType>&);
bool Register_LhatBundledRuntime_Engine_1(LhatProgram*, FLhatBindings&);
void Gather_LhatBundledRuntime_Engine_2(TArray<FLhatNativeType>&);
bool Register_LhatBundledRuntime_Engine_2(LhatProgram*, FLhatBindings&);
void Gather_LhatBundledRuntime_Engine_3(TArray<FLhatNativeType>&);
bool Register_LhatBundledRuntime_Engine_3(LhatProgram*, FLhatBindings&);
void Gather_LhatBundledRuntime_Engine_4(TArray<FLhatNativeType>&);
bool Register_LhatBundledRuntime_Engine_4(LhatProgram*, FLhatBindings&);
void Gather_LhatBundledRuntime_Engine_5(TArray<FLhatNativeType>&);
bool Register_LhatBundledRuntime_Engine_5(LhatProgram*, FLhatBindings&);
void Gather_LhatBundledRuntime_Engine_6(TArray<FLhatNativeType>&);
bool Register_LhatBundledRuntime_Engine_6(LhatProgram*, FLhatBindings&);
void Gather_LhatBundledRuntime_Engine_7(TArray<FLhatNativeType>&);
bool Register_LhatBundledRuntime_Engine_7(LhatProgram*, FLhatBindings&);
void Gather_LhatBundledRuntime_Engine_8(TArray<FLhatNativeType>&);
bool Register_LhatBundledRuntime_Engine_8(LhatProgram*, FLhatBindings&);
void Gather_LhatBundledRuntime_Engine_9(TArray<FLhatNativeType>&);
bool Register_LhatBundledRuntime_Engine_9(LhatProgram*, FLhatBindings&);
void Gather_LhatBundledRuntime_Engine_10(TArray<FLhatNativeType>&);
bool Register_LhatBundledRuntime_Engine_10(LhatProgram*, FLhatBindings&);
void Gather_LhatBundledRuntime_Engine_11(TArray<FLhatNativeType>&);
bool Register_LhatBundledRuntime_Engine_11(LhatProgram*, FLhatBindings&);
void Gather_LhatBundledRuntime_Engine_12(TArray<FLhatNativeType>&);
bool Register_LhatBundledRuntime_Engine_12(LhatProgram*, FLhatBindings&);
void Gather_LhatBundledRuntime_Engine_13(TArray<FLhatNativeType>&);
bool Register_LhatBundledRuntime_Engine_13(LhatProgram*, FLhatBindings&);
void Gather_LhatBundledRuntime_Engine_14(TArray<FLhatNativeType>&);
bool Register_LhatBundledRuntime_Engine_14(LhatProgram*, FLhatBindings&);
void Gather_LhatBundledRuntime_PhysicsCore_0(TArray<FLhatNativeType>&);
bool Register_LhatBundledRuntime_PhysicsCore_0(LhatProgram*, FLhatBindings&);
#if WITH_EDITOR
void Gather_LhatBundledEditor_Engine_0(TArray<FLhatNativeType>&);
bool Register_LhatBundledEditor_Engine_0(LhatProgram*, FLhatBindings&);
#endif
namespace {
void Gather(TArray<FLhatNativeType>& Types) {
    Gather_LhatBundledRuntime_ClothingSystemRuntimeInterface_0(Types);
    Gather_LhatBundledRuntime_Engine_0(Types);
    Gather_LhatBundledRuntime_Engine_1(Types);
    Gather_LhatBundledRuntime_Engine_2(Types);
    Gather_LhatBundledRuntime_Engine_3(Types);
    Gather_LhatBundledRuntime_Engine_4(Types);
    Gather_LhatBundledRuntime_Engine_5(Types);
    Gather_LhatBundledRuntime_Engine_6(Types);
    Gather_LhatBundledRuntime_Engine_7(Types);
    Gather_LhatBundledRuntime_Engine_8(Types);
    Gather_LhatBundledRuntime_Engine_9(Types);
    Gather_LhatBundledRuntime_Engine_10(Types);
    Gather_LhatBundledRuntime_Engine_11(Types);
    Gather_LhatBundledRuntime_Engine_12(Types);
    Gather_LhatBundledRuntime_Engine_13(Types);
    Gather_LhatBundledRuntime_Engine_14(Types);
    Gather_LhatBundledRuntime_PhysicsCore_0(Types);
#if WITH_EDITOR
    Gather_LhatBundledEditor_Engine_0(Types);
#endif
}

bool Register(LhatProgram* P, FLhatBindings& B) {
    if (!Register_LhatBundledRuntime_ClothingSystemRuntimeInterface_0(P, B)) return false;
    if (!Register_LhatBundledRuntime_Engine_0(P, B)) return false;
    if (!Register_LhatBundledRuntime_Engine_1(P, B)) return false;
    if (!Register_LhatBundledRuntime_Engine_2(P, B)) return false;
    if (!Register_LhatBundledRuntime_Engine_3(P, B)) return false;
    if (!Register_LhatBundledRuntime_Engine_4(P, B)) return false;
    if (!Register_LhatBundledRuntime_Engine_5(P, B)) return false;
    if (!Register_LhatBundledRuntime_Engine_6(P, B)) return false;
    if (!Register_LhatBundledRuntime_Engine_7(P, B)) return false;
    if (!Register_LhatBundledRuntime_Engine_8(P, B)) return false;
    if (!Register_LhatBundledRuntime_Engine_9(P, B)) return false;
    if (!Register_LhatBundledRuntime_Engine_10(P, B)) return false;
    if (!Register_LhatBundledRuntime_Engine_11(P, B)) return false;
    if (!Register_LhatBundledRuntime_Engine_12(P, B)) return false;
    if (!Register_LhatBundledRuntime_Engine_13(P, B)) return false;
    if (!Register_LhatBundledRuntime_Engine_14(P, B)) return false;
    if (!Register_LhatBundledRuntime_PhysicsCore_0(P, B)) return false;
#if WITH_EDITOR
    if (!Register_LhatBundledEditor_Engine_0(P, B)) return false;
#endif
    return true;
}
const FLhatNativeBindingProvider Provider{TEXT("LhatBundledEngine"), Gather, Register};
}
const FLhatNativeBindingProvider& LhatBundledEngineProvider() { return Provider; }
