// Generated by GenerateNativeBindings.py; do not edit.
#include "LhatNativeBindings.h"
PRAGMA_DISABLE_DEPRECATION_WARNINGS
#include "Components/MeshComponent.h"
#include "Components/SceneComponent.h"
#include "Engine/Texture2D.h"
#include "GameFramework/Actor.h"
#include "GameFramework/MovementComponent.h"
#include "GameFramework/Pawn.h"
#include "GameFramework/PawnMovementComponent.h"
#include "GameFramework/PhysicsVolume.h"
#include "GameFramework/PlayerController.h"
#include "Kismet/KismetSystemLibrary.h"
#include "Materials/MaterialInterface.h"
#include "UObject/Object.h"
namespace {
static void Call0(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    bool Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    UKismetSystemLibrary::ControlScreensaver(Arg0);
}
static void Call1(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    bool Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    UKismetSystemLibrary::SetVolumeButtonsHandledBySystem(Arg0);
}
static void Call2(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetSystemLibrary::GetVolumeButtonsHandledBySystem();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call3(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    bool Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    UKismetSystemLibrary::SetGamepadsBlockDeviceFeedback(Arg0);
}
static void Call4(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UKismetSystemLibrary::ResetGamepadAssignments();
}
static void Call5(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    int32 Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    UKismetSystemLibrary::ResetGamepadAssignmentToController(Arg0);
}
static void Call6(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    int32 Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetSystemLibrary::IsControllerAssignedToGamepad(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call7(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    int32 Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = UKismetSystemLibrary::GetGamepadControllerName(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call8(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FString Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    int32 Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetSystemLibrary::GetGamepadButtonGlyph(Arg0, Arg1);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call9(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UObject* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    bool Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    UKismetSystemLibrary::SetSuppressViewportTransitionMessage(Arg0, Arg1);
}
static void Call10(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetSystemLibrary::GetDefaultLanguage();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call11(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetSystemLibrary::GetDefaultLocale();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call12(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetSystemLibrary::GetLocalCurrencyCode();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call13(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetSystemLibrary::GetLocalCurrencySymbol();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call14(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UKismetSystemLibrary::RegisterForRemoteNotifications();
}
static void Call15(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UKismetSystemLibrary::UnregisterForRemoteNotifications();
}
static void Call16(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetSystemLibrary::GetCommandLine();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call17(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FString Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    FString Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetSystemLibrary::ParseParam(Arg0, Arg1);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call18(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetSystemLibrary::IsUnattended();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call19(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetSystemLibrary::EndTransaction();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call20(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    int32 Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    UKismetSystemLibrary::CancelTransaction(Arg0);
}
static void Call21(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UObject* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    UKismetSystemLibrary::TransactObject(Arg0);
}
static void Call22(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    UObject* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    UKismetSystemLibrary::SnapshotObject(Arg0);
}
static void Call23(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UMeshComponent*>(B.ReadObject(M, Args[0], UMeshComponent::StaticClass()));
    if (!Self) return;
    bool Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    int32 Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg1)) return;
    const auto Result = Self->GetOverlayMaterial(Arg0, Arg1);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call24(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 4) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UMeshComponent*>(B.ReadObject(M, Args[0], UMeshComponent::StaticClass()));
    if (!Self) return;
    UMaterialInterface* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    bool Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg1)) return;
    int32 Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[3], Arg2)) return;
    Self->SetOverlayMaterial(Arg0, Arg1, Arg2);
}
static void Call25(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UMeshComponent*>(B.ReadObject(M, Args[0], UMeshComponent::StaticClass()));
    if (!Self) return;
    const auto Result = Self->GetOverlayMaterialMaxDrawDistance();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call26(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UMeshComponent*>(B.ReadObject(M, Args[0], UMeshComponent::StaticClass()));
    if (!Self) return;
    float Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    Self->SetOverlayMaterialMaxDrawDistance(Arg0);
}
static void Call27(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 4) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UMeshComponent*>(B.ReadObject(M, Args[0], UMeshComponent::StaticClass()));
    if (!Self) return;
    float Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    bool Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg1)) return;
    int32 Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[3], Arg2)) return;
    Self->PrestreamTextures(Arg0, Arg1, Arg2);
}
static void Call28(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UMeshComponent*>(B.ReadObject(M, Args[0], UMeshComponent::StaticClass()));
    if (!Self) return;
    FName Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    float Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg1)) return;
    Self->SetScalarParameterValueOnMaterials(Arg0, Arg1);
}
static void Call29(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UMeshComponent*>(B.ReadObject(M, Args[0], UMeshComponent::StaticClass()));
    if (!Self) return;
    FName Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[2], Arg1, "Vector")) return;
    Self->SetVectorParameterValueOnMaterials(Arg0, Arg1);
}
static void Call30(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UMeshComponent*>(B.ReadObject(M, Args[0], UMeshComponent::StaticClass()));
    if (!Self) return;
    FName Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    FLinearColor Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[2], Arg1, "LinearColor")) return;
    Self->SetColorParameterValueOnMaterials(Arg0, Arg1);
}
static void Call31(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UMovementComponent*>(B.ReadObject(M, Args[0], UMovementComponent::StaticClass()));
    if (!Self) return;
    const auto Result = Self->GetGravityZ();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call32(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UMovementComponent*>(B.ReadObject(M, Args[0], UMovementComponent::StaticClass()));
    if (!Self) return;
    float Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    const auto Result = Self->IsExceedingMaxSpeed(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call33(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UMovementComponent*>(B.ReadObject(M, Args[0], UMovementComponent::StaticClass()));
    if (!Self) return;
    const auto Result = Self->GetPhysicsVolume();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call34(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UMovementComponent*>(B.ReadObject(M, Args[0], UMovementComponent::StaticClass()));
    if (!Self) return;
    USceneComponent* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    Self->SetUpdatedComponent(Arg0);
}
static void Call35(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UMovementComponent*>(B.ReadObject(M, Args[0], UMovementComponent::StaticClass()));
    if (!Self) return;
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg0, "Vector")) return;
    Self->SetPlaneConstraintNormal(Arg0);
}
static void Call36(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UMovementComponent*>(B.ReadObject(M, Args[0], UMovementComponent::StaticClass()));
    if (!Self) return;
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[2], Arg1, "Vector")) return;
    Self->SetPlaneConstraintFromVectors(Arg0, Arg1);
}
static void Call37(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UMovementComponent*>(B.ReadObject(M, Args[0], UMovementComponent::StaticClass()));
    if (!Self) return;
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg0, "Vector")) return;
    Self->SetPlaneConstraintOrigin(Arg0);
}
static void Call38(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UMovementComponent*>(B.ReadObject(M, Args[0], UMovementComponent::StaticClass()));
    if (!Self) return;
    bool Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    Self->SetPlaneConstraintEnabled(Arg0);
}
static void Call39(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UMovementComponent*>(B.ReadObject(M, Args[0], UMovementComponent::StaticClass()));
    if (!Self) return;
    const auto Result = Self->GetPlaneConstraintNormal();
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call40(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UMovementComponent*>(B.ReadObject(M, Args[0], UMovementComponent::StaticClass()));
    if (!Self) return;
    const auto Result = Self->GetPlaneConstraintOrigin();
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call41(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UMovementComponent*>(B.ReadObject(M, Args[0], UMovementComponent::StaticClass()));
    if (!Self) return;
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg0, "Vector")) return;
    const auto Result = Self->ConstrainDirectionToPlane(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call42(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UMovementComponent*>(B.ReadObject(M, Args[0], UMovementComponent::StaticClass()));
    if (!Self) return;
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg0, "Vector")) return;
    const auto Result = Self->ConstrainLocationToPlane(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call43(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UMovementComponent*>(B.ReadObject(M, Args[0], UMovementComponent::StaticClass()));
    if (!Self) return;
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg0, "Vector")) return;
    const auto Result = Self->ConstrainNormalToPlane(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call44(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UMovementComponent*>(B.ReadObject(M, Args[0], UMovementComponent::StaticClass()));
    if (!Self) return;
    Self->SnapUpdatedComponentToPlane();
}
static void Call45(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APawn*>(B.ReadObject(M, Args[0], APawn::StaticClass()));
    if (!Self) return;
    const auto Result = Self->GetMovementComponent();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call46(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 5) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APawn*>(B.ReadObject(M, Args[0], APawn::StaticClass()));
    if (!Self) return;
    float Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[2], Arg1, "Vector")) return;
    bool Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[3], Arg2)) return;
    AActor* Arg3{};
    if (!LhatUEBindings::Read(M, B, Args[4], Arg3)) return;
    Self->PawnMakeNoise(Arg0, Arg1, Arg2, Arg3);
}
static void Call47(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APawn*>(B.ReadObject(M, Args[0], APawn::StaticClass()));
    if (!Self) return;
    const auto Result = Self->GetLocalViewingPlayerController();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call48(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APawn*>(B.ReadObject(M, Args[0], APawn::StaticClass()));
    if (!Self) return;
    const auto Result = Self->IsLocallyViewed();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call49(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    APawn* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = APawn::GetMovementBaseActor(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call50(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    APawn* Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    const auto Result = APawn::GetMovementBaseOwner(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call51(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APawn*>(B.ReadObject(M, Args[0], APawn::StaticClass()));
    if (!Self) return;
    const auto Result = Self->IsControlled();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call52(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APawn*>(B.ReadObject(M, Args[0], APawn::StaticClass()));
    if (!Self) return;
    const auto Result = Self->IsPawnControlled();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call53(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APawn*>(B.ReadObject(M, Args[0], APawn::StaticClass()));
    if (!Self) return;
    const auto Result = Self->GetControlRotation();
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Rotator")) *AnswerCount = 1;
}
static void Call54(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APawn*>(B.ReadObject(M, Args[0], APawn::StaticClass()));
    if (!Self) return;
    bool Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    bool Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg1)) return;
    Self->SetCanAffectNavigationGeneration(Arg0, Arg1);
}
static void Call55(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APawn*>(B.ReadObject(M, Args[0], APawn::StaticClass()));
    if (!Self) return;
    const auto Result = Self->IsLocallyControlled();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call56(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APawn*>(B.ReadObject(M, Args[0], APawn::StaticClass()));
    if (!Self) return;
    const auto Result = Self->IsPlayerControlled();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call57(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APawn*>(B.ReadObject(M, Args[0], APawn::StaticClass()));
    if (!Self) return;
    const auto Result = Self->IsBotControlled();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call58(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APawn*>(B.ReadObject(M, Args[0], APawn::StaticClass()));
    if (!Self) return;
    const auto Result = Self->GetBaseAimRotation();
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Rotator")) *AnswerCount = 1;
}
static void Call59(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APawn*>(B.ReadObject(M, Args[0], APawn::StaticClass()));
    if (!Self) return;
    Self->DetachFromControllerPendingDestroy();
}
static void Call60(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APawn*>(B.ReadObject(M, Args[0], APawn::StaticClass()));
    if (!Self) return;
    Self->SpawnDefaultController();
}
static void Call61(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 4) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APawn*>(B.ReadObject(M, Args[0], APawn::StaticClass()));
    if (!Self) return;
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg0, "Vector")) return;
    float Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg1)) return;
    bool Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[3], Arg2)) return;
    Self->AddMovementInput(Arg0, Arg1, Arg2);
}
static void Call62(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APawn*>(B.ReadObject(M, Args[0], APawn::StaticClass()));
    if (!Self) return;
    const auto Result = Self->GetPendingMovementInputVector();
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call63(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APawn*>(B.ReadObject(M, Args[0], APawn::StaticClass()));
    if (!Self) return;
    const auto Result = Self->GetLastMovementInputVector();
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call64(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APawn*>(B.ReadObject(M, Args[0], APawn::StaticClass()));
    if (!Self) return;
    const auto Result = Self->ConsumeMovementInputVector();
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call65(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APawn*>(B.ReadObject(M, Args[0], APawn::StaticClass()));
    if (!Self) return;
    float Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    Self->AddControllerPitchInput(Arg0);
}
static void Call66(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APawn*>(B.ReadObject(M, Args[0], APawn::StaticClass()));
    if (!Self) return;
    float Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    Self->AddControllerYawInput(Arg0);
}
static void Call67(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APawn*>(B.ReadObject(M, Args[0], APawn::StaticClass()));
    if (!Self) return;
    float Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    Self->AddControllerRollInput(Arg0);
}
static void Call68(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APawn*>(B.ReadObject(M, Args[0], APawn::StaticClass()));
    if (!Self) return;
    const auto Result = Self->IsMoveInputIgnored();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call69(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPawnMovementComponent*>(B.ReadObject(M, Args[0], UPawnMovementComponent::StaticClass()));
    if (!Self) return;
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg0, "Vector")) return;
    bool Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg1)) return;
    Self->AddInputVector(Arg0, Arg1);
}
static void Call70(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPawnMovementComponent*>(B.ReadObject(M, Args[0], UPawnMovementComponent::StaticClass()));
    if (!Self) return;
    const auto Result = Self->GetPendingInputVector();
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call71(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPawnMovementComponent*>(B.ReadObject(M, Args[0], UPawnMovementComponent::StaticClass()));
    if (!Self) return;
    const auto Result = Self->GetLastInputVector();
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call72(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPawnMovementComponent*>(B.ReadObject(M, Args[0], UPawnMovementComponent::StaticClass()));
    if (!Self) return;
    const auto Result = Self->ConsumeInputVector();
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call73(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPawnMovementComponent*>(B.ReadObject(M, Args[0], UPawnMovementComponent::StaticClass()));
    if (!Self) return;
    const auto Result = Self->IsMoveInputIgnored();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call74(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<UPawnMovementComponent*>(B.ReadObject(M, Args[0], UPawnMovementComponent::StaticClass()));
    if (!Self) return;
    const auto Result = Self->GetPawnOwner();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call75(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APlayerController*>(B.ReadObject(M, Args[0], APlayerController::StaticClass()));
    if (!Self) return;
    const auto Result = Self->GetDeprecatedInputYawScale();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call76(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APlayerController*>(B.ReadObject(M, Args[0], APlayerController::StaticClass()));
    if (!Self) return;
    const auto Result = Self->GetDeprecatedInputPitchScale();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call77(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APlayerController*>(B.ReadObject(M, Args[0], APlayerController::StaticClass()));
    if (!Self) return;
    const auto Result = Self->GetDeprecatedInputRollScale();
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call78(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APlayerController*>(B.ReadObject(M, Args[0], APlayerController::StaticClass()));
    if (!Self) return;
    float Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    Self->SetDeprecatedInputYawScale(Arg0);
}
static void Call79(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    auto* Self = static_cast<APlayerController*>(B.ReadObject(M, Args[0], APlayerController::StaticClass()));
    if (!Self) return;
    float Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg0)) return;
    Self->SetDeprecatedInputPitchScale(Arg0);
}
}
void Gather_LhatBundledRuntime_Engine_10(TArray<FLhatNativeType>& Types)
{
}
bool Register_LhatBundledRuntime_Engine_10(LhatProgram* P, FLhatBindings& B)
{
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "ControlScreensaver", "p^bool^;", Call0, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "SetVolumeButtonsHandledBySystem", "p^bool^;", Call1, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "GetVolumeButtonsHandledBySystem", "f^ -> bool^;", Call2, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "SetGamepadsBlockDeviceFeedback", "p^bool^;", Call3, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "ResetGamepadAssignments", "p^;", Call4, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "ResetGamepadAssignmentToController", "p^number^;", Call5, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "IsControllerAssignedToGamepad", "f^number^ -> bool^;", Call6, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "GetGamepadControllerName", "f^number^ -> string^;", Call7, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "GetGamepadButtonGlyph", "f^string^, number^ -> ue.Engine.Texture2D|nil^;", Call8, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "SetSuppressViewportTransitionMessage", "p^ue.Object|nil^, bool^;", Call9, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "GetDefaultLanguage", "f^ -> string^;", Call10, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "GetDefaultLocale", "f^ -> string^;", Call11, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "GetLocalCurrencyCode", "p^ -> string^;", Call12, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "GetLocalCurrencySymbol", "p^ -> string^;", Call13, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "RegisterForRemoteNotifications", "p^;", Call14, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "UnregisterForRemoteNotifications", "p^;", Call15, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "GetCommandLine", "p^ -> string^;", Call16, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "ParseParam", "f^string^, string^ -> bool^;", Call17, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "IsUnattended", "f^ -> bool^;", Call18, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "EndTransaction", "p^ -> number^;", Call19, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "CancelTransaction", "p^number^;", Call20, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "TransactObject", "p^ue.Object|nil^;", Call21, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetSystemLibrary", "SnapshotObject", "p^ue.Object|nil^;", Call22, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "MeshComponent", "GetOverlayMaterial", "f^self^, bool^, number^ -> ue.Engine.MaterialInterface|nil^;", Call23, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "MeshComponent", "SetOverlayMaterial", "p^self^, ue.Engine.MaterialInterface|nil^, bool^, number^;", Call24, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "MeshComponent", "GetOverlayMaterialMaxDrawDistance", "f^self^ -> number^;", Call25, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "MeshComponent", "SetOverlayMaterialMaxDrawDistance", "p^self^, number^;", Call26, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "MeshComponent", "PrestreamTextures", "p^self^, number^, bool^, number^;", Call27, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "MeshComponent", "SetScalarParameterValueOnMaterials", "p^self^, string^, number^;", Call28, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "MeshComponent", "SetVectorParameterValueOnMaterials", "p^self^, string^, ue.Vector;", Call29, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "MeshComponent", "SetColorParameterValueOnMaterials", "p^self^, string^, ue.LinearColor;", Call30, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "MovementComponent", "GetGravityZ", "f^self^ -> number^;", Call31, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "MovementComponent", "IsExceedingMaxSpeed", "f^self^, number^ -> bool^;", Call32, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "MovementComponent", "GetPhysicsVolume", "f^self^ -> ue.Engine.PhysicsVolume|nil^;", Call33, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "MovementComponent", "SetUpdatedComponent", "p^self^, ue.Engine.SceneComponent|nil^;", Call34, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "MovementComponent", "SetPlaneConstraintNormal", "p^self^, ue.Vector;", Call35, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "MovementComponent", "SetPlaneConstraintFromVectors", "p^self^, ue.Vector, ue.Vector;", Call36, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "MovementComponent", "SetPlaneConstraintOrigin", "p^self^, ue.Vector;", Call37, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "MovementComponent", "SetPlaneConstraintEnabled", "p^self^, bool^;", Call38, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "MovementComponent", "GetPlaneConstraintNormal", "f^self^ -> ue.Vector;", Call39, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "MovementComponent", "GetPlaneConstraintOrigin", "f^self^ -> ue.Vector;", Call40, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "MovementComponent", "ConstrainDirectionToPlane", "f^self^, ue.Vector -> ue.Vector;", Call41, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "MovementComponent", "ConstrainLocationToPlane", "f^self^, ue.Vector -> ue.Vector;", Call42, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "MovementComponent", "ConstrainNormalToPlane", "f^self^, ue.Vector -> ue.Vector;", Call43, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "MovementComponent", "SnapUpdatedComponentToPlane", "p^self^;", Call44, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "Pawn", "GetMovementComponent", "f^self^ -> ue.Engine.PawnMovementComponent|nil^;", Call45, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "Pawn", "PawnMakeNoise", "p^self^, number^, ue.Vector, bool^, ue.Actor|nil^;", Call46, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "Pawn", "GetLocalViewingPlayerController", "f^self^ -> ue.Engine.PlayerController|nil^;", Call47, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "Pawn", "IsLocallyViewed", "f^self^ -> bool^;", Call48, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "Pawn", "GetMovementBaseActor", "f^ue.Engine.Pawn|nil^ -> ue.Actor|nil^;", Call49, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "Pawn", "GetMovementBaseOwner", "f^ue.Engine.Pawn|nil^ -> ue.Object|nil^;", Call50, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "Pawn", "IsControlled", "f^self^ -> bool^;", Call51, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "Pawn", "IsPawnControlled", "f^self^ -> bool^;", Call52, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "Pawn", "GetControlRotation", "f^self^ -> ue.Rotator;", Call53, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "Pawn", "SetCanAffectNavigationGeneration", "p^self^, bool^, bool^;", Call54, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "Pawn", "IsLocallyControlled", "f^self^ -> bool^;", Call55, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "Pawn", "IsPlayerControlled", "f^self^ -> bool^;", Call56, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "Pawn", "IsBotControlled", "f^self^ -> bool^;", Call57, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "Pawn", "GetBaseAimRotation", "f^self^ -> ue.Rotator;", Call58, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "Pawn", "DetachFromControllerPendingDestroy", "p^self^;", Call59, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "Pawn", "SpawnDefaultController", "p^self^;", Call60, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "Pawn", "AddMovementInput", "p^self^, ue.Vector, number^, bool^;", Call61, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "Pawn", "GetPendingMovementInputVector", "f^self^ -> ue.Vector;", Call62, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "Pawn", "GetLastMovementInputVector", "f^self^ -> ue.Vector;", Call63, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "Pawn", "ConsumeMovementInputVector", "p^self^ -> ue.Vector;", Call64, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "Pawn", "AddControllerPitchInput", "p^self^, number^;", Call65, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "Pawn", "AddControllerYawInput", "p^self^, number^;", Call66, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "Pawn", "AddControllerRollInput", "p^self^, number^;", Call67, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "Pawn", "IsMoveInputIgnored", "f^self^ -> bool^;", Call68, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PawnMovementComponent", "AddInputVector", "p^self^, ue.Vector, bool^;", Call69, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PawnMovementComponent", "GetPendingInputVector", "f^self^ -> ue.Vector;", Call70, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PawnMovementComponent", "GetLastInputVector", "f^self^ -> ue.Vector;", Call71, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PawnMovementComponent", "ConsumeInputVector", "p^self^ -> ue.Vector;", Call72, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PawnMovementComponent", "IsMoveInputIgnored", "f^self^ -> bool^;", Call73, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PawnMovementComponent", "GetPawnOwner", "f^self^ -> ue.Engine.Pawn|nil^;", Call74, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PlayerController", "GetDeprecatedInputYawScale", "f^self^ -> number^;", Call75, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PlayerController", "GetDeprecatedInputPitchScale", "f^self^ -> number^;", Call76, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PlayerController", "GetDeprecatedInputRollScale", "f^self^ -> number^;", Call77, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PlayerController", "SetDeprecatedInputYawScale", "p^self^, number^;", Call78, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "PlayerController", "SetDeprecatedInputPitchScale", "p^self^, number^;", Call79, &B)) return false;
    return true;
}
PRAGMA_ENABLE_DEPRECATION_WARNINGS
