// Generated by GenerateNativeBindings.py; do not edit.
#include "LhatNativeBindings.h"
PRAGMA_DISABLE_DEPRECATION_WARNINGS
#include "Kismet/KismetMathLibrary.h"
namespace {
static void Call0(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector2D Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector2D")) return;
    const auto Result = UKismetMathLibrary::ToSign2D(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector2D")) *AnswerCount = 1;
}
static void Call1(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector2D Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector2D")) return;
    const auto Result = UKismetMathLibrary::VSize2D(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call2(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector2D Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector2D")) return;
    const auto Result = UKismetMathLibrary::VSize2DSquared(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call3(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetMathLibrary::Vector_Zero();
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call4(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetMathLibrary::Vector_One();
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call5(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetMathLibrary::Vector_Forward();
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call6(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetMathLibrary::Vector_Backward();
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call7(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetMathLibrary::Vector_Up();
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call8(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetMathLibrary::Vector_Down();
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call9(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetMathLibrary::Vector_Right();
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call10(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 0) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    const auto Result = UKismetMathLibrary::Vector_Left();
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call11(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    double Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    double Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    double Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    const auto Result = UKismetMathLibrary::MakeVector(Arg0, Arg1, Arg2);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call12(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    float Arg0{};
    if (!LhatUEBindings::Read(M, B, Args[0], Arg0)) return;
    float Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    float Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    const auto Result = UKismetMathLibrary::CreateVectorFromYawPitch(Arg0, Arg1, Arg2);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call13(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    const auto Result = UKismetMathLibrary::Conv_VectorToLinearColor(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "LinearColor")) *AnswerCount = 1;
}
static void Call14(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    const auto Result = UKismetMathLibrary::Conv_VectorToTransform(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Transform")) *AnswerCount = 1;
}
static void Call15(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    const auto Result = UKismetMathLibrary::Conv_VectorToVector2D(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector2D")) *AnswerCount = 1;
}
static void Call16(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    const auto Result = UKismetMathLibrary::Conv_VectorToRotator(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Rotator")) *AnswerCount = 1;
}
static void Call17(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    float Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetMathLibrary::RotatorFromAxisAndAngle(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Rotator")) *AnswerCount = 1;
}
static void Call18(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    const auto Result = UKismetMathLibrary::Conv_VectorToQuaternion(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Quat")) *AnswerCount = 1;
}
static void Call19(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    double Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    const auto Result = UKismetMathLibrary::Vector_SlerpVectorToDirection(Arg0, Arg1, Arg2);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call20(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    double Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    const auto Result = UKismetMathLibrary::Vector_SlerpNormals(Arg0, Arg1, Arg2);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call21(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    const auto Result = UKismetMathLibrary::Add_VectorVector(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call22(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    double Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetMathLibrary::Add_VectorFloat(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call23(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    int32 Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetMathLibrary::Add_VectorInt(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call24(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    const auto Result = UKismetMathLibrary::Subtract_VectorVector(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call25(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    double Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetMathLibrary::Subtract_VectorFloat(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call26(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    int32 Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetMathLibrary::Subtract_VectorInt(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call27(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    const auto Result = UKismetMathLibrary::Multiply_VectorVector(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call28(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    double Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetMathLibrary::Multiply_VectorFloat(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call29(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    int32 Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetMathLibrary::Multiply_VectorInt(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call30(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    const auto Result = UKismetMathLibrary::Divide_VectorVector(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call31(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    double Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetMathLibrary::Divide_VectorFloat(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call32(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    int32 Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetMathLibrary::Divide_VectorInt(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call33(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    const auto Result = UKismetMathLibrary::NegateVector(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call34(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    const auto Result = UKismetMathLibrary::EqualExactly_VectorVector(Arg0, Arg1);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call35(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    float Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    const auto Result = UKismetMathLibrary::EqualEqual_VectorVector(Arg0, Arg1, Arg2);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call36(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    const auto Result = UKismetMathLibrary::NotEqualExactly_VectorVector(Arg0, Arg1);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call37(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    float Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    const auto Result = UKismetMathLibrary::NotEqual_VectorVector(Arg0, Arg1, Arg2);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call38(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    const auto Result = UKismetMathLibrary::Dot_VectorVector(Arg0, Arg1);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call39(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    const auto Result = UKismetMathLibrary::Cross_VectorVector(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call40(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FRotator Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Rotator")) return;
    const auto Result = UKismetMathLibrary::GreaterGreater_VectorRotator(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call41(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    float Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    FVector Arg2{};
    if (!LhatUEBindings::ReadValue(M, B, Args[2], Arg2, "Vector")) return;
    const auto Result = UKismetMathLibrary::RotateAngleAxis(Arg0, Arg1, Arg2);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call42(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FRotator Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Rotator")) return;
    const auto Result = UKismetMathLibrary::LessLess_VectorRotator(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call43(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    double Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    double Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    const auto Result = UKismetMathLibrary::ClampVectorSize(Arg0, Arg1, Arg2);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call44(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    double Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    double Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    const auto Result = UKismetMathLibrary::Vector_ClampSize2D(Arg0, Arg1, Arg2);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call45(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    double Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetMathLibrary::Vector_ClampSizeMax(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call46(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    double Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetMathLibrary::Vector_ClampSizeMax2D(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call47(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    const auto Result = UKismetMathLibrary::GetMinElement(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call48(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    const auto Result = UKismetMathLibrary::GetMaxElement(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call49(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    const auto Result = UKismetMathLibrary::Vector_GetAbsMax(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call50(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    const auto Result = UKismetMathLibrary::Vector_GetAbsMin(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call51(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    const auto Result = UKismetMathLibrary::Vector_GetAbs(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call52(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    const auto Result = UKismetMathLibrary::Vector_ComponentMin(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call53(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    const auto Result = UKismetMathLibrary::Vector_ComponentMax(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call54(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    const auto Result = UKismetMathLibrary::Vector_GetSignVector(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call55(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    const auto Result = UKismetMathLibrary::Vector_GetProjection(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call56(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    const auto Result = UKismetMathLibrary::Vector_HeadingAngle(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call57(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    const auto Result = UKismetMathLibrary::Vector_CosineAngle2D(Arg0, Arg1);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call58(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    const auto Result = UKismetMathLibrary::Vector_ToRadians(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call59(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    const auto Result = UKismetMathLibrary::Vector_ToDegrees(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call60(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    const auto Result = UKismetMathLibrary::Vector_UnitCartesianToSpherical(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector2D")) *AnswerCount = 1;
}
static void Call61(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    const auto Result = UKismetMathLibrary::GetDirectionUnitVector(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call62(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    const auto Result = UKismetMathLibrary::Vector_Distance(Arg0, Arg1);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call63(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    const auto Result = UKismetMathLibrary::Vector_DistanceSquared(Arg0, Arg1);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call64(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    const auto Result = UKismetMathLibrary::Vector_Distance2D(Arg0, Arg1);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call65(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    const auto Result = UKismetMathLibrary::Vector_Distance2DSquared(Arg0, Arg1);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call66(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    const auto Result = UKismetMathLibrary::VSize(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call67(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    const auto Result = UKismetMathLibrary::VSizeSquared(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call68(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    const auto Result = UKismetMathLibrary::VSizeXY(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call69(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    const auto Result = UKismetMathLibrary::VSizeXYSquared(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call70(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    float Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetMathLibrary::Vector_IsNearlyZero(Arg0, Arg1);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call71(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    const auto Result = UKismetMathLibrary::Vector_IsZero(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call72(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    const auto Result = UKismetMathLibrary::Vector_IsNAN(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call73(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    float Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetMathLibrary::Vector_IsUniform(Arg0, Arg1);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call74(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    float Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetMathLibrary::Vector_IsUnit(Arg0, Arg1);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call75(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    const auto Result = UKismetMathLibrary::Vector_IsNormal(Arg0);
    if (LhatUEBindings::Write(M, B, Result, Answers[0])) *AnswerCount = 1;
}
static void Call76(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    float Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetMathLibrary::Normal(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call77(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 2) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    float Arg1{};
    if (!LhatUEBindings::Read(M, B, Args[1], Arg1)) return;
    const auto Result = UKismetMathLibrary::Vector_Normal2D(Arg0, Arg1);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call78(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 1) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    const auto Result = UKismetMathLibrary::Vector_NormalUnsafe(Arg0);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
static void Call79(LhatMachine* M, void* Context, const LhatValue* Args, size_t Count, LhatValue* Answers, int* AnswerCount)
{
    check(IsInGameThread());
    auto& B = *static_cast<FLhatBindings*>(Context);
    if (Count != 3) { LhatUEBindings::Fail(M, "Native argument count mismatch"); return; }
    FVector Arg0{};
    if (!LhatUEBindings::ReadValue(M, B, Args[0], Arg0, "Vector")) return;
    FVector Arg1{};
    if (!LhatUEBindings::ReadValue(M, B, Args[1], Arg1, "Vector")) return;
    float Arg2{};
    if (!LhatUEBindings::Read(M, B, Args[2], Arg2)) return;
    const auto Result = UKismetMathLibrary::VLerp(Arg0, Arg1, Arg2);
    if (LhatUEBindings::WriteValue(M, B, Result, Answers[0], "Vector")) *AnswerCount = 1;
}
}
void Gather_LhatBundledRuntime_Engine_5(TArray<FLhatNativeType>& Types)
{
}
bool Register_LhatBundledRuntime_Engine_5(LhatProgram* P, FLhatBindings& B)
{
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "ToSign2D", "f^ue.Vector2D -> ue.Vector2D;", Call0, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "VSize2D", "f^ue.Vector2D -> number^;", Call1, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "VSize2DSquared", "f^ue.Vector2D -> number^;", Call2, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector_Zero", "f^ -> ue.Vector;", Call3, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector_One", "f^ -> ue.Vector;", Call4, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector_Forward", "f^ -> ue.Vector;", Call5, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector_Backward", "f^ -> ue.Vector;", Call6, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector_Up", "f^ -> ue.Vector;", Call7, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector_Down", "f^ -> ue.Vector;", Call8, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector_Right", "f^ -> ue.Vector;", Call9, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector_Left", "f^ -> ue.Vector;", Call10, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "MakeVector", "f^number^, number^, number^ -> ue.Vector;", Call11, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "CreateVectorFromYawPitch", "f^number^, number^, number^ -> ue.Vector;", Call12, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Conv_VectorToLinearColor", "f^ue.Vector -> ue.LinearColor;", Call13, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Conv_VectorToTransform", "f^ue.Vector -> ue.Transform;", Call14, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Conv_VectorToVector2D", "f^ue.Vector -> ue.Vector2D;", Call15, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Conv_VectorToRotator", "f^ue.Vector -> ue.Rotator;", Call16, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "RotatorFromAxisAndAngle", "f^ue.Vector, number^ -> ue.Rotator;", Call17, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Conv_VectorToQuaternion", "f^ue.Vector -> ue.Quat;", Call18, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector_SlerpVectorToDirection", "f^ue.Vector, ue.Vector, number^ -> ue.Vector;", Call19, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector_SlerpNormals", "f^ue.Vector, ue.Vector, number^ -> ue.Vector;", Call20, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Add_VectorVector", "f^ue.Vector, ue.Vector -> ue.Vector;", Call21, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Add_VectorFloat", "f^ue.Vector, number^ -> ue.Vector;", Call22, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Add_VectorInt", "f^ue.Vector, number^ -> ue.Vector;", Call23, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Subtract_VectorVector", "f^ue.Vector, ue.Vector -> ue.Vector;", Call24, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Subtract_VectorFloat", "f^ue.Vector, number^ -> ue.Vector;", Call25, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Subtract_VectorInt", "f^ue.Vector, number^ -> ue.Vector;", Call26, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Multiply_VectorVector", "f^ue.Vector, ue.Vector -> ue.Vector;", Call27, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Multiply_VectorFloat", "f^ue.Vector, number^ -> ue.Vector;", Call28, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Multiply_VectorInt", "f^ue.Vector, number^ -> ue.Vector;", Call29, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Divide_VectorVector", "f^ue.Vector, ue.Vector -> ue.Vector;", Call30, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Divide_VectorFloat", "f^ue.Vector, number^ -> ue.Vector;", Call31, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Divide_VectorInt", "f^ue.Vector, number^ -> ue.Vector;", Call32, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "NegateVector", "f^ue.Vector -> ue.Vector;", Call33, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "EqualExactly_VectorVector", "f^ue.Vector, ue.Vector -> bool^;", Call34, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "EqualEqual_VectorVector", "f^ue.Vector, ue.Vector, number^ -> bool^;", Call35, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "NotEqualExactly_VectorVector", "f^ue.Vector, ue.Vector -> bool^;", Call36, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "NotEqual_VectorVector", "f^ue.Vector, ue.Vector, number^ -> bool^;", Call37, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Dot_VectorVector", "f^ue.Vector, ue.Vector -> number^;", Call38, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Cross_VectorVector", "f^ue.Vector, ue.Vector -> ue.Vector;", Call39, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "GreaterGreater_VectorRotator", "f^ue.Vector, ue.Rotator -> ue.Vector;", Call40, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "RotateAngleAxis", "f^ue.Vector, number^, ue.Vector -> ue.Vector;", Call41, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "LessLess_VectorRotator", "f^ue.Vector, ue.Rotator -> ue.Vector;", Call42, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "ClampVectorSize", "f^ue.Vector, number^, number^ -> ue.Vector;", Call43, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector_ClampSize2D", "f^ue.Vector, number^, number^ -> ue.Vector;", Call44, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector_ClampSizeMax", "f^ue.Vector, number^ -> ue.Vector;", Call45, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector_ClampSizeMax2D", "f^ue.Vector, number^ -> ue.Vector;", Call46, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "GetMinElement", "f^ue.Vector -> number^;", Call47, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "GetMaxElement", "f^ue.Vector -> number^;", Call48, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector_GetAbsMax", "f^ue.Vector -> number^;", Call49, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector_GetAbsMin", "f^ue.Vector -> number^;", Call50, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector_GetAbs", "f^ue.Vector -> ue.Vector;", Call51, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector_ComponentMin", "f^ue.Vector, ue.Vector -> ue.Vector;", Call52, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector_ComponentMax", "f^ue.Vector, ue.Vector -> ue.Vector;", Call53, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector_GetSignVector", "f^ue.Vector -> ue.Vector;", Call54, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector_GetProjection", "f^ue.Vector -> ue.Vector;", Call55, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector_HeadingAngle", "f^ue.Vector -> number^;", Call56, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector_CosineAngle2D", "f^ue.Vector, ue.Vector -> number^;", Call57, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector_ToRadians", "f^ue.Vector -> ue.Vector;", Call58, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector_ToDegrees", "f^ue.Vector -> ue.Vector;", Call59, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector_UnitCartesianToSpherical", "f^ue.Vector -> ue.Vector2D;", Call60, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "GetDirectionUnitVector", "f^ue.Vector, ue.Vector -> ue.Vector;", Call61, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector_Distance", "f^ue.Vector, ue.Vector -> number^;", Call62, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector_DistanceSquared", "f^ue.Vector, ue.Vector -> number^;", Call63, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector_Distance2D", "f^ue.Vector, ue.Vector -> number^;", Call64, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector_Distance2DSquared", "f^ue.Vector, ue.Vector -> number^;", Call65, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "VSize", "f^ue.Vector -> number^;", Call66, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "VSizeSquared", "f^ue.Vector -> number^;", Call67, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "VSizeXY", "f^ue.Vector -> number^;", Call68, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "VSizeXYSquared", "f^ue.Vector -> number^;", Call69, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector_IsNearlyZero", "f^ue.Vector, number^ -> bool^;", Call70, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector_IsZero", "f^ue.Vector -> bool^;", Call71, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector_IsNAN", "f^ue.Vector -> bool^;", Call72, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector_IsUniform", "f^ue.Vector, number^ -> bool^;", Call73, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector_IsUnit", "f^ue.Vector, number^ -> bool^;", Call74, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector_IsNormal", "f^ue.Vector -> bool^;", Call75, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Normal", "f^ue.Vector, number^ -> ue.Vector;", Call76, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector_Normal2D", "f^ue.Vector, number^ -> ue.Vector;", Call77, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "Vector_NormalUnsafe", "f^ue.Vector -> ue.Vector;", Call78, &B)) return false;
    if (!lhat_register_member(P, "ue.Engine", "KismetMathLibrary", "VLerp", "f^ue.Vector, ue.Vector, number^ -> ue.Vector;", Call79, &B)) return false;
    return true;
}
PRAGMA_ENABLE_DEPRECATION_WARNINGS
