#!/usr/bin/env python3
"""Maintainer-only: generate plugin-owned Engine acceleration callbacks from UHT.

The profile chooses precompiled hot APIs, not which APIs reflection may expose.
Consumers need neither this script, a UHT snapshot nor project-generated C++.
"""
import argparse
import json
from pathlib import Path

from GenerateNativeBindings import Generator, RUNTIME, EDITOR, BUILTINS, write_owned

DIRECTORY = "Source/Lhat/Private/Bundled"
MANIFEST = "Bindings/BundledEngineApi.generated.json"


def generate(snapshot, profile):
    generator = Generator(snapshot)
    roots = set(profile["classes"])
    if len(roots) != len(profile["classes"]) or not roots:
        raise ValueError("Bundle profile must contain unique class paths")
    for path in sorted(roots):
        if path not in generator.types:
            raise ValueError(f"Missing bundled class: {path}")
        record = generator.types[path]
        if record["module"] != "Engine" or generator.class_reason(record):
            raise ValueError(f"Bundled root must be a public Engine class: {path}")
    generator.collect(roots)
    original, report = generator.emit()
    files = {}
    units = {RUNTIME: [], EDITOR: []}
    # Reuse exactly the project generator's codecs/callbacks and its bounded TUs.
    for group in (RUNTIME, EDITOR):
        for path, source in original.items():
            prefix = f"Source/{group}/Private/"
            if not path.startswith(prefix) or Path(path).name == group + ".cpp":
                continue
            key = Path(path).stem
            symbol = group.replace("Generated", "Bundled")
            source = source.replace(group, symbol)
            if group == EDITOR:
                source = '#include "CoreMinimal.h"\n#if WITH_EDITOR\n' + source + '#endif\n'
            files[f"{DIRECTORY}/{symbol}_{key}.cpp"] = source
            units[group].append((symbol, key))
    lines = ['// Generated by GenerateBundledBindings.py; do not edit.', '#include "LhatNativeBindings.h"']
    for group in (RUNTIME, EDITOR):
        if group == EDITOR:
            lines.append("#if WITH_EDITOR")
        for symbol, key in units[group]:
            lines += [f"void Gather_{symbol}_{key}(TArray<FLhatNativeType>&);", f"bool Register_{symbol}_{key}(LhatProgram*, FLhatBindings&);"]
        if group == EDITOR:
            lines.append("#endif")
    for gather in (True, False):
        lines += ["namespace {" if gather else "", "void Gather(TArray<FLhatNativeType>& Types) {" if gather else "bool Register(LhatProgram* P, FLhatBindings& B) {"]
        for group in (RUNTIME, EDITOR):
            if group == EDITOR:
                lines.append("#if WITH_EDITOR")
            for symbol, key in units[group]:
                lines.append(f"    Gather_{symbol}_{key}(Types);" if gather else f"    if (!Register_{symbol}_{key}(P, B)) return false;")
            if group == EDITOR:
                lines.append("#endif")
        if not gather:
            lines.append("    return true;")
        lines.append("}")
    lines += ['const FLhatNativeBindingProvider Provider{TEXT("LhatBundledEngine"), Gather, Register};', "}",
              "const FLhatNativeBindingProvider& LhatBundledEngineProvider() { return Provider; }", ""]
    files[f"{DIRECTORY}/LhatBundledBindings.cpp"] = "\n".join(lines)
    # Machine-independent manifest: no absolute paths, project/plugin inventory,
    # or unrelated snapshot hashes. Reused for project-generation subtraction.
    manifest = {"version": 1, "classes": sorted(roots), "groups": report["groups"],
                "types": [{"path": p, "module": generator.type_name(generator.types[p])[0], "name": generator.type_name(generator.types[p])[1]}
                          for p in sorted(generator.registered - BUILTINS.keys())],
                "generated_functions": report["generated_functions"], "skipped": report["skipped"]}
    for group in (RUNTIME, EDITOR):
        dependencies = set(manifest["groups"][group]["dependencies"]) - {"Lhat", RUNTIME}
        manifest["groups"][group]["dependencies"] = sorted(dependencies)
        # A portable Engine bundle must not accidentally drag an optional plugin
        # into every project. Extend deliberately if additional core modules are needed.
        allowed = {"Core", "CoreUObject", "Engine"}
        all_dependencies = dependencies | set(manifest["groups"][group]["editor_dependencies"])
        for module in all_dependencies - allowed:
            root = generator.include_roots.get(module)
            if root is None or "/Engine/Source/Runtime/" not in root.as_posix():
                raise ValueError(f"Bundled dependency is not a built-in Engine runtime module: {module}")
    files[MANIFEST] = json.dumps(manifest, ensure_ascii=False, indent=2) + "\n"
    return files, manifest


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--snapshot", type=Path, required=True)
    parser.add_argument("--plugin", type=Path, default=Path(__file__).resolve().parents[1])
    args = parser.parse_args()
    plugin = args.plugin.resolve(strict=True)
    profile = json.loads((plugin / "Bindings/BundledEngineApi.json").read_text(encoding="utf-8"))
    files, manifest = generate(args.snapshot.resolve(strict=True), profile)
    write_owned(plugin / "Lhat.uplugin", files, False,
                manifest_relative=f"{DIRECTORY}/LhatBundledFiles.json", allowed_roots=[DIRECTORY + "/", MANIFEST])
    print(json.dumps(manifest["groups"], indent=2))


if __name__ == "__main__":
    main()
